# Generated by Django 5.0.3 on 2024-03-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Prenume')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nume de familie')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Număr de telefon')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='Adresă de e-mail')),
                ('company', models.CharField(blank=True, max_length=50, null=True, verbose_name='Companie')),
                ('job_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Funcție')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Localitate')),
                ('street_address', models.CharField(blank=True, max_length=40, null=True, verbose_name='Stradă')),
                ('street_number', models.IntegerField(blank=True, null=True, verbose_name='Număr stradă')),
                ('block', models.CharField(blank=True, max_length=4, null=True, verbose_name='Bloc')),
                ('scale', models.CharField(blank=True, max_length=3, null=True, verbose_name='Scară')),
                ('apartment_number', models.IntegerField(blank=True, null=True, verbose_name='Număr apartament')),
                ('county', models.CharField(blank=True, max_length=20, null=True, verbose_name='Județ')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Țară')),
                ('document_type', models.CharField(blank=True, choices=[('Carte de identitate', 'Carte de identitate'), ('Pașaport', 'Pașaport'), ('Alt document', 'Alt document')], null=True, verbose_name='Tip document')),
                ('id_series_nr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Serie / Număr')),
                ('cnp', models.CharField(blank=True, max_length=13, null=True, verbose_name='CNP')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Data emiterii')),
                ('passport_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Țara emitentă (doar pentru pașaport)')),
                ('contact_type', models.CharField(blank=True, choices=[('Administrator', 'Administrator'), ('Agent imobiliar', 'Agent imobiliar'), ('Chiriaș', 'Chiriaș'), ('Colaborator', 'Colaborator'), ('Cumpărător', 'Cumpărător'), ('Dezvoltator imobiliar', 'Dezvoltator imobiliar'), ('Investitor', 'Investitor'), ('Proprietar', 'Proprietar'), ('Reprezentant', 'Reprezentant')], null=True, verbose_name='Tip contact')),
                ('contact_category', models.CharField(blank=True, choices=[('Client vechi', 'Client vechi'), ('Concurență', 'Concurență'), ('Cunoștință', 'Cunoștință'), ('De evitat', 'De evitat'), ('Important', 'Important'), ('Neserios', 'Neserios')], null=True, verbose_name='Categorie')),
                ('other_details', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Alte detalii')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data adăugării')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ultimei actualizări')),
            ],
        ),
    ]
