# Generated by Django 5.0.2 on 2024-03-01 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Prenume⋆')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nume de familie⋆')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Numărul de telefon trebuie să conțină doar cifre \n        și să aibă între 10 și 14 caractere legate, fără spații.', regex='^\\d{10,14}$')], verbose_name='Număr de telefon')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='Adresă de e-mail')),
                ('company', models.CharField(blank=True, max_length=50, null=True, verbose_name='Companie')),
                ('job_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Funcție')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Localitate')),
                ('street_address', models.CharField(blank=True, max_length=40, null=True, verbose_name='Stradă')),
                ('street_number', models.IntegerField(blank=True, null=True, verbose_name='Număr stradă')),
                ('block', models.CharField(blank=True, max_length=4, null=True, verbose_name='Bloc')),
                ('scale', models.CharField(blank=True, max_length=3, null=True, verbose_name='Scară')),
                ('apartment_number', models.IntegerField(blank=True, null=True, verbose_name='Număr apartament')),
                ('county', models.CharField(blank=True, max_length=20, null=True, verbose_name='Județ')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Țară')),
                ('document_type', models.CharField(blank=True, choices=[('Carte de identitate', 'Carte de identitate'), ('Pașaport', 'Pașaport'), ('Alt document', 'Alt document')], max_length=20, null=True, verbose_name='Tip document')),
                ('id_series', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Seria documentului trebuie să conțină doar caractere alfanumerice majuscule.', regex='^[A-Z0-9]+$')], verbose_name='Serie')),
                ('id_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Numărul documentului trebuie să conțină doar caractere alfanumerice.', regex='^[A-Z0-9]+$')], verbose_name='Număr')),
                ('passport_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Țara emitentă (doar pentru pașaport).')),
                ('cnp', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='CNP-ul trebuie să conțină doar cifre și să aibă exact 13 caractere.', regex='^\\d{13}$')], verbose_name='CNP')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Data emiterii')),
                ('other_details', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Alte detalii')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data adăugării')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ultimei actualizări')),
            ],
        ),
    ]
