# Generated by Django 5.0.2 on 2024-03-02 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Numărul documentului trebuie să conțină doar cifre.', regex='^[0-9]+$')], verbose_name='Număr'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id_series',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Seria documentului trebuie să conțină doar litere majuscule.', regex='^[A-Z]+$')], verbose_name='Serie'),
        ),
    ]
