# Generated by Django 5.0.2 on 2024-03-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_id_number_alter_contact_id_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Prenume'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Nume de familie'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='passport_country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Țara emitentă (doar pentru pașaport)'),
        ),
    ]
