# Generated by Django 5.0.2 on 2024-03-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cnp',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='CNP'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Adresă de e-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Număr'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id_series',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Număr de telefon'),
        ),
    ]
