# Generated by Django 5.0.2 on 2024-03-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contact_email_alter_contact_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='id_series',
        ),
        migrations.AddField(
            model_name='contact',
            name='id_series_nr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Serie / Număr'),
        ),
    ]
