# Generated by Django 5.0.2 on 2024-03-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_remove_contact_id_number_remove_contact_id_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id_series_nr',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Serie / Număr'),
        ),
    ]
