# Generated by Django 5.0.2 on 2024-03-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_alter_contact_id_series_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_category',
            field=models.CharField(blank=True, choices=[('Client vechi', 'Client vechi'), ('Concurență', 'Concurență'), ('Cunoștință', 'Cunoștință'), ('De evitat', 'De evitat'), ('Important', 'Important'), ('Neserios', 'Neserios')], max_length=13, null=True, verbose_name='Categorie'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('Administrator', 'Administrator'), ('Agent imobiliar', 'Agent imobiliar'), ('Chiriaș', 'Chiriaș'), ('Colaborator', 'Colaborator'), ('Cumpărător', 'Cumpărător'), ('Dezvoltator imobiliar', 'Dezvoltator imobiliar'), ('Investitor', 'Investitor'), ('Proprietar', 'Proprietar'), ('Reprezentant', 'Reprezentant')], max_length=22, null=True, verbose_name='Tip contact'),
        ),
    ]
