# Generated by Django 5.0.3 on 2024-03-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_contact_contact_category_contact_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_category',
            field=models.CharField(blank=True, choices=[('Client vechi', 'Client vechi'), ('Concurență', 'Concurență'), ('Cunoștință', 'Cunoștință'), ('De evitat', 'De evitat'), ('Important', 'Important'), ('Neserios', 'Neserios')], null=True, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('Administrator', 'Administrator'), ('Agent imobiliar', 'Agent imobiliar'), ('Chiriaș', 'Chiriaș'), ('Colaborator', 'Colaborator'), ('Cumpărător', 'Cumpărător'), ('Dezvoltator imobiliar', 'Dezvoltator imobiliar'), ('Investitor', 'Investitor'), ('Proprietar', 'Proprietar'), ('Reprezentant', 'Reprezentant')], null=True, verbose_name='Tip contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Carte de identitate', 'Carte de identitate'), ('Pașaport', 'Pașaport'), ('Alt document', 'Alt document')], null=True, verbose_name='Tip document'),
        ),
    ]
