# Generated by Django 5.0.2 on 2024-02-16 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=35, verbose_name='Nume client')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Numărul de telefon trebuie să conțină doar cifre și să aibă între 10 și 14 caractere legate, fără spații!', regex='^\\d{10,14}$')], verbose_name='Număr de telefon')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='Adresă de e-mail')),
                ('lead_labels', models.CharField(blank=True, choices=[('De revenit', 'De revenit'), ('Nu răspunde', 'Nu răspunde'), ('Trimis e-mail', 'Trimis e-mail'), ('Trimis contract', 'Trimis contract'), ('Vizionare', 'Vizionare'), ('Negociere', 'Negociere'), ('Pregătire acte', 'Pregătire acte'), ('Avans', 'Avans'), ('Tranzacție', 'Tranzacție'), ('Caut proprietate', 'Caut proprietate'), ('În discuții', 'În discuții'), ('Se mai gândește', 'Se mai gândește'), ('Nu este valabil', 'Nu este valabil'), ('Nu mă ocup', 'Nu mă ocup')], max_length=20, verbose_name='Etichete cerere')),
                ('lead_urgency', models.CharField(blank=True, choices=[('Critic', 'Critic'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('Nu', 'Nu')], max_length=10, verbose_name='Urgență cerere')),
                ('lead_details', models.TextField(max_length=255, verbose_name='Detalii cerere')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data introducerii')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ultimei actualizări')),
                ('agent_notes', models.TextField(blank=True, max_length=255, null=True, verbose_name='Notițe agent')),
                ('assigned_listings', models.ManyToManyField(blank=True, to='listings.listing', verbose_name='Proprietăți asociate')),
            ],
        ),
    ]
