# Generated by Django 5.0.4 on 2024-04-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentlead',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Notițe proprii'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='other_details',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Alte detalii'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Notițe proprii'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='other_details',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Alte detalii'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Notițe proprii'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='other_details',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Alte detalii'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Notițe proprii'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='other_details',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Alte detalii'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Notițe proprii'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='other_details',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Alte detalii'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Notițe proprii'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='other_details',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Alte detalii'),
        ),
    ]
