# Generated by Django 5.0.3 on 2024-03-31 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('leads', '0002_remove_apartmentlead_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentlead',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='apartmentlead',
            name='deadline_time',
        ),
        migrations.RemoveField(
            model_name='commercialspacelead',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='commercialspacelead',
            name='deadline_time',
        ),
        migrations.RemoveField(
            model_name='houselead',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='houselead',
            name='deadline_time',
        ),
        migrations.RemoveField(
            model_name='industrialspacelead',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='industrialspacelead',
            name='deadline_time',
        ),
        migrations.RemoveField(
            model_name='officespacelead',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='officespacelead',
            name='deadline_time',
        ),
        migrations.RemoveField(
            model_name='terrainlead',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='terrainlead',
            name='deadline_time',
        ),
        migrations.AddField(
            model_name='apartmentlead',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termen limită'),
        ),
        migrations.AddField(
            model_name='commercialspacelead',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termen limită'),
        ),
        migrations.AddField(
            model_name='houselead',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termen limită'),
        ),
        migrations.AddField(
            model_name='industrialspacelead',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termen limită'),
        ),
        migrations.AddField(
            model_name='officespacelead',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termen limită'),
        ),
        migrations.AddField(
            model_name='terrainlead',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termen limită'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='apartment_type',
            field=models.CharField(choices=[('Apartament', 'Apartament'), ('Garsonieră', 'Garsonieră'), ('Penthouse', 'Penthouse')], verbose_name='Tip apartament'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contact asociat'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='destination',
            field=models.CharField(choices=[('Rezidențială', 'Rezidențială'), ('Comercială', 'Comercială'), ('Birouri', 'Birouri')], verbose_name='Destinație'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip cerere'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Activă', verbose_name='Status cerere'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='transaction_type',
            field=models.CharField(choices=[('Cumpărare', 'Cumpărare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contact asociat'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip cerere'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='space_type',
            field=models.CharField(choices=[('Bloc de apartamente', 'Bloc de apartamente'), ('Clădire birouri', 'Clădire birouri'), ('Casă / Vilă', 'Casă / Vilă'), ('Centru comercial', 'Centru comercial'), ('Hală / Depozit', 'Hală / Depozit'), ('Stradal', 'Stradal')], verbose_name='Tip imobil'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Activă', verbose_name='Status cerere'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='transaction_type',
            field=models.CharField(choices=[('Cumpărare', 'Cumpărare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contact asociat'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='house_type',
            field=models.CharField(choices=[('Individuală', 'Individuală'), ('Vilă', 'Vilă'), ('Calcan', 'Calcan'), ('Duplex', 'Duplex'), ('Triplex', 'Triplex'), ('Înșiruită', 'Înșiruită')], verbose_name='Tip casă'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip cerere'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Activă', verbose_name='Status cerere'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='transaction_type',
            field=models.CharField(choices=[('Cumpărare', 'Cumpărare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contact asociat'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip cerere'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='space_type',
            field=models.CharField(choices=[('Producție grea', 'Producție grea'), ('Producție ușoară', 'Producție ușoară'), ('Depozit distribuție', 'Depozit distribuție'), ('Depozit general', 'Depozit general'), ('Cercetare și dezvoltare', 'Cercetare și dezvoltare'), ('Centru de date', 'Centru de date'), ('Showroom', 'Showroom')], verbose_name='Tip spațiu'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Activă', verbose_name='Status cerere'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='transaction_type',
            field=models.CharField(choices=[('Cumpărare', 'Cumpărare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contact asociat'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip cerere'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='space_type',
            field=models.CharField(choices=[('Bloc de apartamente', 'Bloc de apartamente'), ('Clădire birouri', 'Clădire birouri'), ('Casă / Vilă', 'Casă / Vilă'), ('Centru comercial', 'Centru comercial'), ('Hală / Depozit', 'Hală / Depozit'), ('Stradal', 'Stradal')], verbose_name='Tip imobil'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Activă', verbose_name='Status cerere'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='transaction_type',
            field=models.CharField(choices=[('Cumpărare', 'Cumpărare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='classification',
            field=models.CharField(choices=[('Intravilan', 'Intravilan'), ('Extravilan', 'Extravilan')], verbose_name='Clasificare'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contact asociat'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='destination',
            field=models.CharField(choices=[('Rezidențială', 'Rezidențială'), ('Comercială', 'Comercială'), ('Industrială', 'Industrială'), ('Agricolă', 'Agricolă'), ('Horeca / Retail', 'Horeca / Retail'), ('Spital / Clinică', 'Spital / Clinică'), ('Benzinărie', 'Benzinărie'), ('Spălătorie auto', 'Spălătorie auto'), ('De vacanță', 'De vacanță')], verbose_name='Destinație'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip cerere'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Activă', verbose_name='Status cerere'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='terrain_type',
            field=models.CharField(choices=[('Construcții', 'Construcții'), ('Agricol', 'Agricol'), ('Pădure', 'Pădure')], verbose_name='Tip teren'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='transaction_type',
            field=models.CharField(choices=[('Cumpărare', 'Cumpărare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție'),
        ),
    ]
