# Generated by Django 5.0.2 on 2024-03-01 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('leads', '0002_apartmentlead_commercialspacelead_houselead_and_more'),
        ('listings', '0002_apartment_commercialspace_house_industrialspace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentlead',
            name='assigned_listings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_apartment_key', to='listings.industrialspace', verbose_name='Proprietăți asociate'),
        ),
        migrations.AddField(
            model_name='apartmentlead',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contact asociat'),
        ),
        migrations.AddField(
            model_name='apartmentlead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_apartment_key', to=settings.AUTH_USER_MODEL, verbose_name='Agent asociat'),
        ),
        migrations.AddField(
            model_name='commercialspacelead',
            name='assigned_listings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_commercial_space_key', to='listings.industrialspace', verbose_name='Proprietăți asociate'),
        ),
        migrations.AddField(
            model_name='commercialspacelead',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contact asociat'),
        ),
        migrations.AddField(
            model_name='commercialspacelead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_commercial_space_key', to=settings.AUTH_USER_MODEL, verbose_name='Agent asociat'),
        ),
        migrations.AddField(
            model_name='houselead',
            name='assigned_listings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_house_key', to='listings.industrialspace', verbose_name='Proprietăți asociate'),
        ),
        migrations.AddField(
            model_name='houselead',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contact asociat'),
        ),
        migrations.AddField(
            model_name='houselead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_house_key', to=settings.AUTH_USER_MODEL, verbose_name='Agent asociat'),
        ),
        migrations.AddField(
            model_name='industrialspacelead',
            name='assigned_listings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_industrial_space_key', to='listings.industrialspace', verbose_name='Proprietăți asociate'),
        ),
        migrations.AddField(
            model_name='industrialspacelead',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contact asociat'),
        ),
        migrations.AddField(
            model_name='industrialspacelead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_industrial_space_key', to=settings.AUTH_USER_MODEL, verbose_name='Agent asociat'),
        ),
        migrations.AddField(
            model_name='officespacelead',
            name='assigned_listings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_office_space_key', to='listings.industrialspace', verbose_name='Proprietăți asociate'),
        ),
        migrations.AddField(
            model_name='officespacelead',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contact asociat'),
        ),
        migrations.AddField(
            model_name='officespacelead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_office_space_key', to=settings.AUTH_USER_MODEL, verbose_name='Agent asociat'),
        ),
        migrations.AddField(
            model_name='terrainlead',
            name='assigned_listings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_terrain_key', to='listings.industrialspace', verbose_name='Proprietăți asociate'),
        ),
        migrations.AddField(
            model_name='terrainlead',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contact asociat'),
        ),
        migrations.AddField(
            model_name='terrainlead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_terrain_key', to=settings.AUTH_USER_MODEL, verbose_name='Agent asociat'),
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
