# Generated by Django 5.0.2 on 2024-03-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_apartmentlead_assigned_listings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentlead',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='apartmentlead',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='apartmentlead',
            name='client_phone',
        ),
        migrations.RemoveField(
            model_name='commercialspacelead',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='commercialspacelead',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='commercialspacelead',
            name='client_phone',
        ),
        migrations.RemoveField(
            model_name='houselead',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='houselead',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='houselead',
            name='client_phone',
        ),
        migrations.RemoveField(
            model_name='industrialspacelead',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='industrialspacelead',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='industrialspacelead',
            name='client_phone',
        ),
        migrations.RemoveField(
            model_name='officespacelead',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='officespacelead',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='officespacelead',
            name='client_phone',
        ),
        migrations.RemoveField(
            model_name='terrainlead',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='terrainlead',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='terrainlead',
            name='client_phone',
        ),
    ]
