# Generated by Django 5.0.4 on 2024-06-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_apartmentlead_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialspacelead',
            name='space_type',
            field=models.CharField(choices=[('Bloc de apartamente', 'Bloc de apartamente'), ('Clădire de birouri', 'Clădire de birouri'), ('Casă / Vilă', 'Casă / Vilă'), ('Centru comercial', 'Centru comercial'), ('Hală / Depozit', 'Hală / Depozit'), ('Stradal', 'Stradal')], verbose_name='Tip imobil'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='minimum_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Suprafață minimă (mp)'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='space_type',
            field=models.CharField(choices=[('Bloc de apartamente', 'Bloc de apartamente'), ('Clădire de birouri', 'Clădire de birouri'), ('Casă / Vilă', 'Casă / Vilă'), ('Centru comercial', 'Centru comercial'), ('Hală / Depozit', 'Hală / Depozit'), ('Stradal', 'Stradal')], verbose_name='Tip imobil'),
        ),
    ]
