# Generated by Django 5.0.2 on 2024-03-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_remove_apartmentlead_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentlead',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', max_length=18, verbose_name='Tip proprietate⋆'),
        ),
        migrations.AddField(
            model_name='commercialspacelead',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', max_length=18, verbose_name='Tip proprietate⋆'),
        ),
        migrations.AddField(
            model_name='houselead',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', max_length=18, verbose_name='Tip proprietate⋆'),
        ),
        migrations.AddField(
            model_name='industrialspacelead',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', max_length=18, verbose_name='Tip proprietate⋆'),
        ),
        migrations.AddField(
            model_name='officespacelead',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', max_length=18, verbose_name='Tip proprietate⋆'),
        ),
        migrations.AddField(
            model_name='terrainlead',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', max_length=18, verbose_name='Tip proprietate⋆'),
        ),
    ]
