# Generated by Django 5.0.4 on 2024-06-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_commercialspacelead_space_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentlead',
            name='custom_id',
            field=models.CharField(default='AP0', editable=False, max_length=15, verbose_name='ID'),
        ),
    ]
