# Generated by Django 5.0.3 on 2024-04-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_apartmentlead_property_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentlead',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='commercialspacelead',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='houselead',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='industrialspacelead',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='officespacelead',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='terrainlead',
            name='deadline',
        ),
        migrations.AddField(
            model_name='apartmentlead',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data limită'),
        ),
        migrations.AddField(
            model_name='apartmentlead',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora limită'),
        ),
        migrations.AddField(
            model_name='commercialspacelead',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data limită'),
        ),
        migrations.AddField(
            model_name='commercialspacelead',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora limită'),
        ),
        migrations.AddField(
            model_name='houselead',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data limită'),
        ),
        migrations.AddField(
            model_name='houselead',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora limită'),
        ),
        migrations.AddField(
            model_name='industrialspacelead',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data limită'),
        ),
        migrations.AddField(
            model_name='industrialspacelead',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora limită'),
        ),
        migrations.AddField(
            model_name='officespacelead',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data limită'),
        ),
        migrations.AddField(
            model_name='officespacelead',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora limită'),
        ),
        migrations.AddField(
            model_name='terrainlead',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data limită'),
        ),
        migrations.AddField(
            model_name='terrainlead',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora limită'),
        ),
    ]
