# Generated by Django 5.0.2 on 2024-03-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_apartmentlead_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentlead',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buget alocat'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='urgency',
            field=models.CharField(choices=[('Critic', 'Critic'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('Nu', 'Nu')], default='Normal', max_length=8, verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buget alocat'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='urgency',
            field=models.CharField(choices=[('Critic', 'Critic'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('Nu', 'Nu')], default='Normal', max_length=8, verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buget alocat'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='urgency',
            field=models.CharField(choices=[('Critic', 'Critic'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('Nu', 'Nu')], default='Normal', max_length=8, verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buget alocat'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='urgency',
            field=models.CharField(choices=[('Critic', 'Critic'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('Nu', 'Nu')], default='Normal', max_length=8, verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buget alocat'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='urgency',
            field=models.CharField(choices=[('Critic', 'Critic'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('Nu', 'Nu')], default='Normal', max_length=8, verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buget alocat'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='urgency',
            field=models.CharField(choices=[('Critic', 'Critic'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('Nu', 'Nu')], default='Normal', max_length=8, verbose_name='Urgență'),
        ),
    ]
