# Generated by Django 5.0.3 on 2024-03-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_apartmentlead_budget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentlead',
            old_name='excluding_top_floor',
            new_name='excluded_top_floor',
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='urgency',
            field=models.CharField(choices=[('Nu', 'Nu'), ('Normal', 'Normal'), ('Critic', 'Critic'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('14 zile', '14 zile'), ('1 lună', '1 lună')], default='Normal', max_length=8, verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='urgency',
            field=models.CharField(choices=[('Nu', 'Nu'), ('Normal', 'Normal'), ('Critic', 'Critic'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('14 zile', '14 zile'), ('1 lună', '1 lună')], default='Normal', max_length=8, verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='urgency',
            field=models.CharField(choices=[('Nu', 'Nu'), ('Normal', 'Normal'), ('Critic', 'Critic'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('14 zile', '14 zile'), ('1 lună', '1 lună')], default='Normal', max_length=8, verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='urgency',
            field=models.CharField(choices=[('Nu', 'Nu'), ('Normal', 'Normal'), ('Critic', 'Critic'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('14 zile', '14 zile'), ('1 lună', '1 lună')], default='Normal', max_length=8, verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='urgency',
            field=models.CharField(choices=[('Nu', 'Nu'), ('Normal', 'Normal'), ('Critic', 'Critic'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('14 zile', '14 zile'), ('1 lună', '1 lună')], default='Normal', max_length=8, verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='urgency',
            field=models.CharField(choices=[('Nu', 'Nu'), ('Normal', 'Normal'), ('Critic', 'Critic'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('14 zile', '14 zile'), ('1 lună', '1 lună')], default='Normal', max_length=8, verbose_name='Urgență'),
        ),
    ]
