# Generated by Django 5.0.4 on 2024-06-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_apartmentlead_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselead',
            name='custom_id',
            field=models.CharField(default='CA', editable=False, max_length=15, verbose_name='ID'),
        ),
    ]
