# Generated by Django 5.0.3 on 2024-03-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_rename_excluding_top_floor_apartmentlead_excluded_top_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentlead',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], max_length=20, verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='urgency',
            field=models.CharField(choices=[('DA', 'DA'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('NU', 'NU')], default='Normal', max_length=8, verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], max_length=20, verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='urgency',
            field=models.CharField(choices=[('DA', 'DA'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('NU', 'NU')], default='Normal', max_length=8, verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], max_length=20, verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='urgency',
            field=models.CharField(choices=[('DA', 'DA'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('NU', 'NU')], default='Normal', max_length=8, verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], max_length=20, verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='urgency',
            field=models.CharField(choices=[('DA', 'DA'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('NU', 'NU')], default='Normal', max_length=8, verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], max_length=20, verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='urgency',
            field=models.CharField(choices=[('DA', 'DA'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('NU', 'NU')], default='Normal', max_length=8, verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], max_length=20, verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='urgency',
            field=models.CharField(choices=[('DA', 'DA'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('NU', 'NU')], default='Normal', max_length=8, verbose_name='Urgență'),
        ),
    ]
