# Generated by Django 5.0.3 on 2024-03-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_apartmentlead_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentlead',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termen limită'),
        ),
        migrations.AddField(
            model_name='commercialspacelead',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termen limită'),
        ),
        migrations.AddField(
            model_name='houselead',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termen limită'),
        ),
        migrations.AddField(
            model_name='industrialspacelead',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termen limită'),
        ),
        migrations.AddField(
            model_name='officespacelead',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termen limită'),
        ),
        migrations.AddField(
            model_name='terrainlead',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termen limită'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='ap_compart',
            field=models.CharField(blank=True, choices=[('Decomandat', 'Decomandat'), ('Semidecomandat', 'Semidecomandat'), ('Nedecomandat', 'Nedecomandat'), ('Circular', 'Circular'), ('Vagon', 'Vagon')], null=True, verbose_name='Compartimentare'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='apartment_type',
            field=models.CharField(choices=[('Apartament', 'Apartament'), ('Garsonieră', 'Garsonieră'), ('Penthouse', 'Penthouse')], verbose_name='Tip apartament⋆'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='comfort',
            field=models.CharField(blank=True, choices=[('Lux', 'Lux'), ('1', '1'), ('2', '2'), ('3', '3')], null=True, verbose_name='Confort'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='construction_status',
            field=models.CharField(blank=True, choices=[('Finalizată', 'Finalizată'), ('La gri', 'La gri'), ('La roșu', 'La roșu'), ('Structură', 'Structură'), ('Proiect', 'Proiect'), ('În construcție', 'În construcție'), ('De demolat', 'De demolat')], null=True, verbose_name='Stadiu construcție'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='destination',
            field=models.CharField(choices=[('Rezidențială', 'Rezidențială'), ('Comercială', 'Comercială'), ('Birouri', 'Birouri')], verbose_name='Destinație⋆'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='floor',
            field=models.CharField(blank=True, choices=[('Demisol', 'Demisol'), ('Parter', 'Parter'), ('Parter înalt', 'Parter înalt'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('Mansardă', 'Mansardă'), ('Ultimele 2 etaje', 'Ultimele 2 etaje')], null=True, verbose_name='Etaj'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='furniture',
            field=models.CharField(blank=True, choices=[('Mobilat complet', 'Mobilat complet'), ('Mobilat lux', 'Mobilat lux'), ('Mobilat parțial', 'Mobilat parțial'), ('Nemobilat', 'Nemobilat')], null=True, verbose_name='Mobilier'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='interior_finishes',
            field=models.CharField(blank=True, choices=[('Finisat modern', 'Finisat modern'), ('Finisat', 'Finisat'), ('Finisat clasic', 'Finisat clasic'), ('Semifinisat', 'Semifinisat'), ('Renovabil', 'Renovabil'), ('Nefinisat', 'Nefinisat')], null=True, verbose_name='Stare interior'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='labels',
            field=models.CharField(blank=True, choices=[('De revenit', 'De revenit'), ('Nu răspunde', 'Nu răspunde'), ('Trimis e-mail', 'Trimis e-mail'), ('Trimis contract', 'Trimis contract'), ('Vizionare', 'Vizionare'), ('Negociere', 'Negociere'), ('Pregătire acte', 'Pregătire acte'), ('Avans', 'Avans'), ('Tranzacție', 'Tranzacție'), ('Caut proprietate', 'Caut proprietate'), ('În discuții', 'În discuții'), ('Se mai gândește', 'Se mai gândește'), ('Nu este valabilă', 'Nu este valabilă'), ('Nu mă ocup', 'Nu mă ocup')], null=True, verbose_name='Etichete'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='orientation',
            field=models.CharField(blank=True, choices=[('Nord', 'Nord'), ('Sud', 'Sud'), ('Vest', 'Vest'), ('Est', 'Est'), ('Nord-Vest', 'Nord-Vest'), ('Nord-Est', 'Nord-Est'), ('Sud-Vest', 'Sud-Vest'), ('Sud-Est', 'Sud-Est'), ('Nord-Sud', 'Nord-Sud'), ('Vest-Est', 'Vest-Est')], null=True, verbose_name='Orientare'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit ipotecar', 'Credit ipotecar'), ('Credit Prima Casă', 'Credit Prima Casă'), ('Rate la dezvoltator', 'Rate la dezvoltator')], null=True, verbose_name='Modalitate plată'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Activă', verbose_name='Status cerere⋆'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='transaction_type',
            field=models.CharField(choices=[('Cumpărare', 'Cumpărare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție⋆'),
        ),
        migrations.AlterField(
            model_name='apartmentlead',
            name='urgency',
            field=models.CharField(choices=[('DA', 'DA'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('NU', 'NU')], default='Normal', verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='destination',
            field=models.CharField(blank=True, choices=[('Comercială', 'Comercială'), ('Birouri', 'Birouri'), ('Horeca / Retail', 'Horeca / Retail'), ('Magazin prezentare', 'Magazin prezentare'), ('Showroom', 'Showroom'), ('Bancă', 'Bancă'), ('Farmacie', 'Farmacie')], null=True, verbose_name='Destinație'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='floor',
            field=models.CharField(blank=True, choices=[('Demisol', 'Demisol'), ('Parter', 'Parter'), ('Parter înalt', 'Parter înalt'), ('Mezanin', 'Mezanin'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('Mansardă', 'Mansardă'), ('Ultimele 2 etaje', 'Ultimele 2 etaje')], null=True, verbose_name='Etaj'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='labels',
            field=models.CharField(blank=True, choices=[('De revenit', 'De revenit'), ('Nu răspunde', 'Nu răspunde'), ('Trimis e-mail', 'Trimis e-mail'), ('Trimis contract', 'Trimis contract'), ('Vizionare', 'Vizionare'), ('Negociere', 'Negociere'), ('Pregătire acte', 'Pregătire acte'), ('Avans', 'Avans'), ('Tranzacție', 'Tranzacție'), ('Caut proprietate', 'Caut proprietate'), ('În discuții', 'În discuții'), ('Se mai gândește', 'Se mai gândește'), ('Nu este valabilă', 'Nu este valabilă'), ('Nu mă ocup', 'Nu mă ocup')], null=True, verbose_name='Etichete'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit ipotecar', 'Credit ipotecar'), ('Credit Prima Casă', 'Credit Prima Casă'), ('Rate la dezvoltator', 'Rate la dezvoltator')], null=True, verbose_name='Modalitate plată'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='pedestrian_traffic',
            field=models.CharField(blank=True, choices=[('Intens', 'Intens'), ('Moderat', 'Moderat'), ('Fără trafic pietonal', 'Fără trafic pietonal')], null=True, verbose_name='Trafic pietonal'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='space_compart',
            field=models.CharField(blank=True, choices=[('Open-space', 'Open-space'), ('Compartimentat', 'Compartimentat'), ('Parțial compartimentat', 'Parțial compartimentat'), ('Flexibil', 'Flexibil')], null=True, verbose_name='Compartimentare'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='space_type',
            field=models.CharField(choices=[('Bloc de apartamente', 'Bloc de apartamente'), ('Clădire birouri', 'Clădire birouri'), ('Casă / Vilă', 'Casă / Vilă'), ('Centru comercial', 'Centru comercial'), ('Hală / Depozit', 'Hală / Depozit'), ('Stradal', 'Stradal')], verbose_name='Tip imobil⋆'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Activă', verbose_name='Status cerere⋆'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='transaction_type',
            field=models.CharField(choices=[('Cumpărare', 'Cumpărare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție⋆'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='urgency',
            field=models.CharField(choices=[('DA', 'DA'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('NU', 'NU')], default='Normal', verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='construction_status',
            field=models.CharField(blank=True, choices=[('Finalizată', 'Finalizată'), ('La gri', 'La gri'), ('La roșu', 'La roșu'), ('Structură', 'Structură'), ('Proiect', 'Proiect'), ('În construcție', 'În construcție'), ('De demolat', 'De demolat')], null=True, verbose_name='Stadiu construcție'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='destination',
            field=models.CharField(blank=True, choices=[('Rezidențială', 'Rezidențială'), ('Comercială', 'Comercială'), ('Birouri', 'Birouri')], null=True, verbose_name='Destinație'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='furniture',
            field=models.CharField(blank=True, choices=[('Mobilat complet', 'Mobilat complet'), ('Mobilat lux', 'Mobilat lux'), ('Mobilat parțial', 'Mobilat parțial'), ('Nemobilat', 'Nemobilat')], null=True, verbose_name='Mobilier'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='house_type',
            field=models.CharField(choices=[('Individuală', 'Individuală'), ('Vilă', 'Vilă'), ('Calcan', 'Calcan'), ('Duplex', 'Duplex'), ('Triplex', 'Triplex'), ('Înșiruită', 'Înșiruită')], verbose_name='Tip casă⋆'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='interior_finishes',
            field=models.CharField(blank=True, choices=[('Finisat modern', 'Finisat modern'), ('Finisat', 'Finisat'), ('Finisat clasic', 'Finisat clasic'), ('Semifinisat', 'Semifinisat'), ('Renovabil', 'Renovabil'), ('Nefinisat', 'Nefinisat')], null=True, verbose_name='Stare interior'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='labels',
            field=models.CharField(blank=True, choices=[('De revenit', 'De revenit'), ('Nu răspunde', 'Nu răspunde'), ('Trimis e-mail', 'Trimis e-mail'), ('Trimis contract', 'Trimis contract'), ('Vizionare', 'Vizionare'), ('Negociere', 'Negociere'), ('Pregătire acte', 'Pregătire acte'), ('Avans', 'Avans'), ('Tranzacție', 'Tranzacție'), ('Caut proprietate', 'Caut proprietate'), ('În discuții', 'În discuții'), ('Se mai gândește', 'Se mai gândește'), ('Nu este valabilă', 'Nu este valabilă'), ('Nu mă ocup', 'Nu mă ocup')], null=True, verbose_name='Etichete'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit ipotecar', 'Credit ipotecar'), ('Credit Prima Casă', 'Credit Prima Casă'), ('Rate la dezvoltator', 'Rate la dezvoltator')], null=True, verbose_name='Modalitate plată'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Activă', verbose_name='Status cerere⋆'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='transaction_type',
            field=models.CharField(choices=[('Cumpărare', 'Cumpărare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție⋆'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='urgency',
            field=models.CharField(choices=[('DA', 'DA'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('NU', 'NU')], default='Normal', verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='destination',
            field=models.CharField(blank=True, choices=[('Producție', 'Producție'), ('Depozitare', 'Depozitare'), ('Prezentare', 'Prezentare')], null=True, verbose_name='Destinație'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='floor',
            field=models.CharField(blank=True, choices=[('Demisol', 'Demisol'), ('Parter', 'Parter'), ('Parter înalt', 'Parter înalt'), ('1', '1'), ('2', '2'), ('3', '3'), ('Mansardă', 'Mansardă')], null=True, verbose_name='Etaj'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='labels',
            field=models.CharField(blank=True, choices=[('De revenit', 'De revenit'), ('Nu răspunde', 'Nu răspunde'), ('Trimis e-mail', 'Trimis e-mail'), ('Trimis contract', 'Trimis contract'), ('Vizionare', 'Vizionare'), ('Negociere', 'Negociere'), ('Pregătire acte', 'Pregătire acte'), ('Avans', 'Avans'), ('Tranzacție', 'Tranzacție'), ('Caut proprietate', 'Caut proprietate'), ('În discuții', 'În discuții'), ('Se mai gândește', 'Se mai gândește'), ('Nu este valabilă', 'Nu este valabilă'), ('Nu mă ocup', 'Nu mă ocup')], null=True, verbose_name='Etichete'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit ipotecar', 'Credit ipotecar'), ('Credit Prima Casă', 'Credit Prima Casă'), ('Rate la dezvoltator', 'Rate la dezvoltator')], null=True, verbose_name='Modalitate plată'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='space_compart',
            field=models.CharField(blank=True, choices=[('Open-space', 'Open-space'), ('Compartimentat', 'Compartimentat'), ('Parțial compartimentat', 'Parțial compartimentat'), ('Flexibil', 'Flexibil')], null=True, verbose_name='Compartimentare'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='space_type',
            field=models.CharField(choices=[('Producție grea', 'Producție grea'), ('Producție ușoară', 'Producție ușoară'), ('Depozit distribuție', 'Depozit distribuție'), ('Depozit general', 'Depozit general'), ('Cercetare și dezvoltare', 'Cercetare și dezvoltare'), ('Centru de date', 'Centru de date'), ('Showroom', 'Showroom')], verbose_name='Tip spațiu⋆'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Activă', verbose_name='Status cerere⋆'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='transaction_type',
            field=models.CharField(choices=[('Cumpărare', 'Cumpărare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție⋆'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='urgency',
            field=models.CharField(choices=[('DA', 'DA'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('NU', 'NU')], default='Normal', verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='floor',
            field=models.CharField(blank=True, choices=[('Demisol', 'Demisol'), ('Parter', 'Parter'), ('Parter înalt', 'Parter înalt'), ('Mezanin', 'Mezanin'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('Mansardă', 'Mansardă'), ('Ultimele 2 etaje', 'Ultimele 2 etaje')], null=True, verbose_name='Etaj'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='labels',
            field=models.CharField(blank=True, choices=[('De revenit', 'De revenit'), ('Nu răspunde', 'Nu răspunde'), ('Trimis e-mail', 'Trimis e-mail'), ('Trimis contract', 'Trimis contract'), ('Vizionare', 'Vizionare'), ('Negociere', 'Negociere'), ('Pregătire acte', 'Pregătire acte'), ('Avans', 'Avans'), ('Tranzacție', 'Tranzacție'), ('Caut proprietate', 'Caut proprietate'), ('În discuții', 'În discuții'), ('Se mai gândește', 'Se mai gândește'), ('Nu este valabilă', 'Nu este valabilă'), ('Nu mă ocup', 'Nu mă ocup')], null=True, verbose_name='Etichete'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit ipotecar', 'Credit ipotecar'), ('Credit Prima Casă', 'Credit Prima Casă'), ('Rate la dezvoltator', 'Rate la dezvoltator')], null=True, verbose_name='Modalitate plată'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='space_class',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], null=True, verbose_name='Clasă'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='space_compart',
            field=models.CharField(blank=True, choices=[('Open-space', 'Open-space'), ('Compartimentat', 'Compartimentat'), ('Parțial compartimentat', 'Parțial compartimentat'), ('Flexibil', 'Flexibil')], null=True, verbose_name='Compartimentare'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='space_type',
            field=models.CharField(choices=[('Bloc de apartamente', 'Bloc de apartamente'), ('Clădire birouri', 'Clădire birouri'), ('Casă / Vilă', 'Casă / Vilă'), ('Centru comercial', 'Centru comercial'), ('Hală / Depozit', 'Hală / Depozit'), ('Stradal', 'Stradal')], verbose_name='Tip imobil⋆'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Activă', verbose_name='Status cerere⋆'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='transaction_type',
            field=models.CharField(choices=[('Cumpărare', 'Cumpărare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție⋆'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='urgency',
            field=models.CharField(choices=[('DA', 'DA'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('NU', 'NU')], default='Normal', verbose_name='Urgență'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='classification',
            field=models.CharField(choices=[('Intravilan', 'Intravilan'), ('Extravilan', 'Extravilan')], verbose_name='Clasificare⋆'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='destination',
            field=models.CharField(choices=[('Rezidențială', 'Rezidențială'), ('Comercială', 'Comercială'), ('Industrială', 'Industrială'), ('Agricolă', 'Agricolă'), ('Horeca / Retail', 'Horeca / Retail'), ('Spital / Clinică', 'Spital / Clinică'), ('Benzinărie', 'Benzinărie'), ('Spălătorie auto', 'Spălătorie auto'), ('De vacanță', 'De vacanță')], verbose_name='Destinație⋆'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='labels',
            field=models.CharField(blank=True, choices=[('De revenit', 'De revenit'), ('Nu răspunde', 'Nu răspunde'), ('Trimis e-mail', 'Trimis e-mail'), ('Trimis contract', 'Trimis contract'), ('Vizionare', 'Vizionare'), ('Negociere', 'Negociere'), ('Pregătire acte', 'Pregătire acte'), ('Avans', 'Avans'), ('Tranzacție', 'Tranzacție'), ('Caut proprietate', 'Caut proprietate'), ('În discuții', 'În discuții'), ('Se mai gândește', 'Se mai gândește'), ('Nu este valabilă', 'Nu este valabilă'), ('Nu mă ocup', 'Nu mă ocup')], null=True, verbose_name='Etichete'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='opening_to',
            field=models.CharField(blank=True, choices=[('Șosea', 'Șosea'), ('Drum principal', 'Drum principal'), ('DN', 'DN'), ('Autostradă', 'Autostradă'), ('Șoseaua de centură', 'Șoseaua de centură'), ('Lac', 'Lac'), ('Pădure', 'Pădure'), ('Drum de servitute', 'Drum de servitute')], null=True, verbose_name='Deschidere la'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit ipotecar', 'Credit ipotecar'), ('Credit Prima Casă', 'Credit Prima Casă'), ('Rate la dezvoltator', 'Rate la dezvoltator')], null=True, verbose_name='Modalitate plată'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Activă', verbose_name='Status cerere⋆'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='terrain_type',
            field=models.CharField(choices=[('Construcții', 'Construcții'), ('Agricol', 'Agricol'), ('Pădure', 'Pădure')], verbose_name='Tip teren⋆'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='transaction_type',
            field=models.CharField(choices=[('Cumpărare', 'Cumpărare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție⋆'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='unit',
            field=models.CharField(blank=True, choices=[('mp', 'mp'), ('ar', 'ar'), ('ha', 'ha')], null=True, verbose_name='Unitate suprafață'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='urgency',
            field=models.CharField(choices=[('DA', 'DA'), ('3 zile', '3 zile'), ('7 zile', '7 zile'), ('Normal', 'Normal'), ('14 zile', '14 zile'), ('1 lună', '1 lună'), ('NU', 'NU')], default='Normal', verbose_name='Urgență'),
        ),
    ]
