# Generated by Django 5.0.4 on 2024-06-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_houselead_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrainlead',
            name='custom_id',
            field=models.CharField(default='TR', editable=False, max_length=15, verbose_name='ID'),
        ),
    ]
