# Generated by Django 5.0.4 on 2024-06-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_terrainlead_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrainlead',
            name='custom_id',
            field=models.CharField(editable=False, max_length=15, unique=True, verbose_name='ID'),
        ),
    ]
