# Generated by Django 5.0.4 on 2024-06-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_terrainlead_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialspacelead',
            name='custom_id',
            field=models.CharField(default='SC', editable=False, max_length=15, verbose_name='ID'),
        ),
    ]
