# Generated by Django 5.0.4 on 2024-06-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_alter_commercialspacelead_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='officespacelead',
            name='custom_id',
            field=models.CharField(default='SB', editable=False, max_length=15, verbose_name='ID'),
        ),
    ]
