# Generated by Django 5.0.4 on 2024-06-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_alter_officespacelead_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrialspacelead',
            name='custom_id',
            field=models.CharField(default='SI', editable=False, max_length=15, verbose_name='ID'),
        ),
    ]
