# Generated by Django 5.0.4 on 2024-06-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_alter_industrialspacelead_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentlead',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='commercialspacelead',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='houselead',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='industrialspacelead',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='officespacelead',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='terrainlead',
            name='labels',
        ),
        migrations.AddField(
            model_name='apartmentlead',
            name='label',
            field=models.CharField(blank=True, choices=[('De revenit', 'De revenit'), ('Nu răspunde', 'Nu răspunde'), ('Trimis e-mail', 'Trimis e-mail'), ('Trimis contract', 'Trimis contract'), ('Vizionare', 'Vizionare'), ('Negociere', 'Negociere'), ('Pregătire acte', 'Pregătire acte'), ('Avans', 'Avans'), ('Tranzacție', 'Tranzacție'), ('Caut proprietate', 'Caut proprietate'), ('În discuții', 'În discuții'), ('Se mai gândește', 'Se mai gândește'), ('Nu este valabilă', 'Nu este valabilă'), ('Nu mă ocup', 'Nu mă ocup')], null=True, verbose_name='Etichetă'),
        ),
        migrations.AddField(
            model_name='commercialspacelead',
            name='label',
            field=models.CharField(blank=True, choices=[('De revenit', 'De revenit'), ('Nu răspunde', 'Nu răspunde'), ('Trimis e-mail', 'Trimis e-mail'), ('Trimis contract', 'Trimis contract'), ('Vizionare', 'Vizionare'), ('Negociere', 'Negociere'), ('Pregătire acte', 'Pregătire acte'), ('Avans', 'Avans'), ('Tranzacție', 'Tranzacție'), ('Caut proprietate', 'Caut proprietate'), ('În discuții', 'În discuții'), ('Se mai gândește', 'Se mai gândește'), ('Nu este valabilă', 'Nu este valabilă'), ('Nu mă ocup', 'Nu mă ocup')], null=True, verbose_name='Etichetă'),
        ),
        migrations.AddField(
            model_name='houselead',
            name='label',
            field=models.CharField(blank=True, choices=[('De revenit', 'De revenit'), ('Nu răspunde', 'Nu răspunde'), ('Trimis e-mail', 'Trimis e-mail'), ('Trimis contract', 'Trimis contract'), ('Vizionare', 'Vizionare'), ('Negociere', 'Negociere'), ('Pregătire acte', 'Pregătire acte'), ('Avans', 'Avans'), ('Tranzacție', 'Tranzacție'), ('Caut proprietate', 'Caut proprietate'), ('În discuții', 'În discuții'), ('Se mai gândește', 'Se mai gândește'), ('Nu este valabilă', 'Nu este valabilă'), ('Nu mă ocup', 'Nu mă ocup')], null=True, verbose_name='Etichetă'),
        ),
        migrations.AddField(
            model_name='industrialspacelead',
            name='label',
            field=models.CharField(blank=True, choices=[('De revenit', 'De revenit'), ('Nu răspunde', 'Nu răspunde'), ('Trimis e-mail', 'Trimis e-mail'), ('Trimis contract', 'Trimis contract'), ('Vizionare', 'Vizionare'), ('Negociere', 'Negociere'), ('Pregătire acte', 'Pregătire acte'), ('Avans', 'Avans'), ('Tranzacție', 'Tranzacție'), ('Caut proprietate', 'Caut proprietate'), ('În discuții', 'În discuții'), ('Se mai gândește', 'Se mai gândește'), ('Nu este valabilă', 'Nu este valabilă'), ('Nu mă ocup', 'Nu mă ocup')], null=True, verbose_name='Etichetă'),
        ),
        migrations.AddField(
            model_name='officespacelead',
            name='label',
            field=models.CharField(blank=True, choices=[('De revenit', 'De revenit'), ('Nu răspunde', 'Nu răspunde'), ('Trimis e-mail', 'Trimis e-mail'), ('Trimis contract', 'Trimis contract'), ('Vizionare', 'Vizionare'), ('Negociere', 'Negociere'), ('Pregătire acte', 'Pregătire acte'), ('Avans', 'Avans'), ('Tranzacție', 'Tranzacție'), ('Caut proprietate', 'Caut proprietate'), ('În discuții', 'În discuții'), ('Se mai gândește', 'Se mai gândește'), ('Nu este valabilă', 'Nu este valabilă'), ('Nu mă ocup', 'Nu mă ocup')], null=True, verbose_name='Etichetă'),
        ),
        migrations.AddField(
            model_name='terrainlead',
            name='label',
            field=models.CharField(blank=True, choices=[('De revenit', 'De revenit'), ('Nu răspunde', 'Nu răspunde'), ('Trimis e-mail', 'Trimis e-mail'), ('Trimis contract', 'Trimis contract'), ('Vizionare', 'Vizionare'), ('Negociere', 'Negociere'), ('Pregătire acte', 'Pregătire acte'), ('Avans', 'Avans'), ('Tranzacție', 'Tranzacție'), ('Caut proprietate', 'Caut proprietate'), ('În discuții', 'În discuții'), ('Se mai gândește', 'Se mai gândește'), ('Nu este valabilă', 'Nu este valabilă'), ('Nu mă ocup', 'Nu mă ocup')], null=True, verbose_name='Etichetă'),
        ),
    ]
