# Generated by Django 5.0.4 on 2024-06-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_remove_apartmentlead_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentlead',
            name='destination',
            field=models.CharField(blank=True, choices=[('Rezidențială', 'Rezidențială'), ('Comercială', 'Comercială'), ('Birouri', 'Birouri')], null=True, verbose_name='Destinație'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='classification',
            field=models.CharField(blank=True, choices=[('Intravilan', 'Intravilan'), ('Extravilan', 'Extravilan')], null=True, verbose_name='Clasificare'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='destination',
            field=models.CharField(blank=True, choices=[('Rezidențială', 'Rezidențială'), ('Comercială', 'Comercială'), ('Industrială', 'Industrială'), ('Agricolă', 'Agricolă'), ('Horeca / Retail', 'Horeca / Retail'), ('Spital / Clinică', 'Spital / Clinică'), ('Benzinărie', 'Benzinărie'), ('Spălătorie auto', 'Spălătorie auto'), ('De vacanță', 'De vacanță')], null=True, verbose_name='Destinație'),
        ),
    ]
