# Generated by Django 5.0.4 on 2024-06-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_alter_apartmentlead_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentlead',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buget (€)'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buget (€)'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buget (€)'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buget (€)'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buget (€)'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buget (€)'),
        ),
    ]
