# Generated by Django 5.0.4 on 2024-06-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_alter_apartmentlead_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentlead',
            name='property_type',
            field=models.CharField(choices=[('Apartament', 'Apartament'), ('Casă', 'Casă'), ('Teren', 'Teren'), ('Spațiu comercial', 'Spațiu comercial'), ('Spațiu de birouri', 'Spațiu de birouri'), ('Spațiu industrial', 'Spațiu industrial')], verbose_name='Tip cerere'),
        ),
        migrations.AlterField(
            model_name='commercialspacelead',
            name='property_type',
            field=models.CharField(choices=[('Apartament', 'Apartament'), ('Casă', 'Casă'), ('Teren', 'Teren'), ('Spațiu comercial', 'Spațiu comercial'), ('Spațiu de birouri', 'Spațiu de birouri'), ('Spațiu industrial', 'Spațiu industrial')], verbose_name='Tip cerere'),
        ),
        migrations.AlterField(
            model_name='houselead',
            name='property_type',
            field=models.CharField(choices=[('Apartament', 'Apartament'), ('Casă', 'Casă'), ('Teren', 'Teren'), ('Spațiu comercial', 'Spațiu comercial'), ('Spațiu de birouri', 'Spațiu de birouri'), ('Spațiu industrial', 'Spațiu industrial')], verbose_name='Tip cerere'),
        ),
        migrations.AlterField(
            model_name='industrialspacelead',
            name='property_type',
            field=models.CharField(choices=[('Apartament', 'Apartament'), ('Casă', 'Casă'), ('Teren', 'Teren'), ('Spațiu comercial', 'Spațiu comercial'), ('Spațiu de birouri', 'Spațiu de birouri'), ('Spațiu industrial', 'Spațiu industrial')], verbose_name='Tip cerere'),
        ),
        migrations.AlterField(
            model_name='officespacelead',
            name='property_type',
            field=models.CharField(choices=[('Apartament', 'Apartament'), ('Casă', 'Casă'), ('Teren', 'Teren'), ('Spațiu comercial', 'Spațiu comercial'), ('Spațiu de birouri', 'Spațiu de birouri'), ('Spațiu industrial', 'Spațiu industrial')], verbose_name='Tip cerere'),
        ),
        migrations.AlterField(
            model_name='terrainlead',
            name='property_type',
            field=models.CharField(choices=[('Apartament', 'Apartament'), ('Casă', 'Casă'), ('Teren', 'Teren'), ('Spațiu comercial', 'Spațiu comercial'), ('Spațiu de birouri', 'Spațiu de birouri'), ('Spațiu industrial', 'Spațiu industrial')], verbose_name='Tip cerere'),
        ),
    ]
