# Generated by Django 5.0.3 on 2024-03-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='ap_compart',
            field=models.CharField(choices=[('Decomandat', 'Decomandat'), ('Semidecomandat', 'Semidecomandat'), ('Nedecomandat', 'Nedecomandat'), ('Circular', 'Circular'), ('Vagon', 'Vagon')], verbose_name='Compartimentare'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartment_nr',
            field=models.IntegerField(verbose_name='Număr apartament'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartment_type',
            field=models.CharField(choices=[('Apartament', 'Apartament'), ('Garsonieră', 'Garsonieră'), ('Penthouse', 'Penthouse')], verbose_name='Tip apartament'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='construction_year',
            field=models.IntegerField(verbose_name='Anul construcției'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.CharField(choices=[('Demisol', 'Demisol'), ('Parter', 'Parter'), ('Parter înalt', 'Parter înalt'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('Mansardă', 'Mansardă'), ('Ultimele 2 etaje', 'Ultimele 2 etaje')], verbose_name='Etaj'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='interior_finishes',
            field=models.CharField(choices=[('Finisat modern', 'Finisat modern'), ('Finisat', 'Finisat'), ('Finisat clasic', 'Finisat clasic'), ('Semifinisat', 'Semifinisat'), ('Necesită renovare', 'Necesită renovare'), ('Nefinisat', 'Nefinisat')], verbose_name='Stare interior'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='nr_floors',
            field=models.IntegerField(verbose_name='Număr etaje'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preț tranzacționare'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rooms_number',
            field=models.IntegerField(verbose_name='Număr camere'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Incompletă', 'Incompletă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Incompletă', verbose_name='Status proprietate'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='street_address',
            field=models.CharField(max_length=40, verbose_name='Stradă'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='street_nr',
            field=models.IntegerField(verbose_name='Număr stradă'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='transaction_type',
            field=models.CharField(choices=[('Vânzare', 'Vânzare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='useful_surface',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Suprafață utilă (mp)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='zone',
            field=models.CharField(max_length=20, verbose_name='Zonă'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='construction_year',
            field=models.IntegerField(verbose_name='Anul construcției'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='floor',
            field=models.CharField(choices=[('Demisol', 'Demisol'), ('Parter', 'Parter'), ('Parter înalt', 'Parter înalt'), ('Mezanin', 'Mezanin'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('Mansardă', 'Mansardă'), ('Ultimele 2 etaje', 'Ultimele 2 etaje')], verbose_name='Etaj'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='nr_floors',
            field=models.IntegerField(verbose_name='Număr etaje'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preț tranzacționare'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='space_nr',
            field=models.IntegerField(verbose_name='Număr spațiu'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='space_type',
            field=models.CharField(choices=[('Bloc de apartamente', 'Bloc de apartamente'), ('Clădire birouri', 'Clădire birouri'), ('Casă / Vilă', 'Casă / Vilă'), ('Centru comercial', 'Centru comercial'), ('Hală / Depozit', 'Hală / Depozit'), ('Stradal', 'Stradal')], verbose_name='Tip imobil'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Incompletă', 'Incompletă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Incompletă', verbose_name='Status proprietate'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='street_address',
            field=models.CharField(max_length=40, verbose_name='Stradă'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='street_nr',
            field=models.IntegerField(verbose_name='Număr stradă'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='transaction_type',
            field=models.CharField(choices=[('Vânzare', 'Vânzare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='useful_surface',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Suprafață utilă (mp)'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='zone',
            field=models.CharField(max_length=20, verbose_name='Zonă'),
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='house',
            name='construction_year',
            field=models.IntegerField(verbose_name='Anul construcției'),
        ),
        migrations.AlterField(
            model_name='house',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('Individuală', 'Individuală'), ('Vilă', 'Vilă'), ('Calcan', 'Calcan'), ('Duplex', 'Duplex'), ('Triplex', 'Triplex'), ('Înșiruită', 'Înșiruită')], verbose_name='Tip casă'),
        ),
        migrations.AlterField(
            model_name='house',
            name='interior_finishes',
            field=models.CharField(choices=[('Finisat modern', 'Finisat modern'), ('Finisat', 'Finisat'), ('Finisat clasic', 'Finisat clasic'), ('Semifinisat', 'Semifinisat'), ('Necesită renovare', 'Necesită renovare'), ('Nefinisat', 'Nefinisat')], verbose_name='Stare interior'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preț tranzacționare'),
        ),
        migrations.AlterField(
            model_name='house',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate'),
        ),
        migrations.AlterField(
            model_name='house',
            name='rooms_number',
            field=models.IntegerField(verbose_name='Număr camere'),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Incompletă', 'Incompletă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Incompletă', verbose_name='Status proprietate'),
        ),
        migrations.AlterField(
            model_name='house',
            name='street_address',
            field=models.CharField(max_length=40, verbose_name='Stradă'),
        ),
        migrations.AlterField(
            model_name='house',
            name='street_nr',
            field=models.IntegerField(verbose_name='Număr stradă'),
        ),
        migrations.AlterField(
            model_name='house',
            name='transaction_type',
            field=models.CharField(choices=[('Vânzare', 'Vânzare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție'),
        ),
        migrations.AlterField(
            model_name='house',
            name='useful_surface',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Suprafață utilă (mp)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='zone',
            field=models.CharField(max_length=20, verbose_name='Zonă'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='construction_year',
            field=models.IntegerField(verbose_name='Anul construcției'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='inside_height',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Înălțime interioară (m)'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preț tranzacționare'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='space_type',
            field=models.CharField(choices=[('Producție grea', 'Producție grea'), ('Producție ușoară', 'Producție ușoară'), ('Depozit distribuție', 'Depozit distribuție'), ('Depozit general', 'Depozit general'), ('Cercetare și dezvoltare', 'Cercetare și dezvoltare'), ('Centru de date', 'Centru de date'), ('Showroom', 'Showroom')], verbose_name='Tip spațiu'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Incompletă', 'Incompletă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Incompletă', verbose_name='Status proprietate'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='street_address',
            field=models.CharField(max_length=40, verbose_name='Stradă'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='street_nr',
            field=models.IntegerField(verbose_name='Număr stradă'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='terrain_surface',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Suprafață teren (mp)'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='transaction_type',
            field=models.CharField(choices=[('Vânzare', 'Vânzare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='useful_surface',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Suprafață utilă (mp)'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='zone',
            field=models.CharField(max_length=20, verbose_name='Zonă'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='construction_status',
            field=models.CharField(choices=[('Finalizată', 'Finalizată'), ('La gri', 'La gri'), ('La roșu', 'La roșu'), ('Structură', 'Structură'), ('Proiect', 'Proiect'), ('În construcție', 'În construcție'), ('De demolat', 'De demolat')], verbose_name='Stadiu construcție'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='construction_year',
            field=models.IntegerField(verbose_name='Anul construcției'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='interior_finishes',
            field=models.CharField(choices=[('Finisat modern', 'Finisat modern'), ('Finisat', 'Finisat'), ('Finisat clasic', 'Finisat clasic'), ('Semifinisat', 'Semifinisat'), ('Necesită renovare', 'Necesită renovare'), ('Nefinisat', 'Nefinisat')], verbose_name='Stare interior'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='nr_floors',
            field=models.IntegerField(verbose_name='Număr etaje'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Incompletă', 'Incompletă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Incompletă', verbose_name='Status proprietate'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='street_address',
            field=models.CharField(max_length=40, verbose_name='Stradă'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='street_nr',
            field=models.IntegerField(verbose_name='Număr stradă'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='total_surface_offices',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Suprafață totală birouri (mp)'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='zone',
            field=models.CharField(max_length=20, verbose_name='Zonă'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='construction_year',
            field=models.IntegerField(verbose_name='Anul construcției'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='floor',
            field=models.CharField(choices=[('Demisol', 'Demisol'), ('Parter', 'Parter'), ('Parter înalt', 'Parter înalt'), ('Mezanin', 'Mezanin'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('Mansardă', 'Mansardă'), ('Ultimele 2 etaje', 'Ultimele 2 etaje')], verbose_name='Etaj'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='nr_floors',
            field=models.IntegerField(verbose_name='Număr etaje'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preț tranzacționare'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='space_nr',
            field=models.IntegerField(verbose_name='Număr spațiu'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='space_type',
            field=models.CharField(choices=[('Bloc de apartamente', 'Bloc de apartamente'), ('Clădire birouri', 'Clădire birouri'), ('Casă / Vilă', 'Casă / Vilă'), ('Centru comercial', 'Centru comercial'), ('Hală / Depozit', 'Hală / Depozit'), ('Stradal', 'Stradal')], verbose_name='Tip imobil'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Incompletă', 'Incompletă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Incompletă', verbose_name='Status proprietate'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='street_address',
            field=models.CharField(max_length=40, verbose_name='Stradă'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='street_nr',
            field=models.IntegerField(verbose_name='Număr stradă'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='total_surface_offices',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Suprafață totală birouri (mp)'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='transaction_type',
            field=models.CharField(choices=[('Vânzare', 'Vânzare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='useful_surface',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Suprafață utilă (mp)'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='zone',
            field=models.CharField(max_length=20, verbose_name='Zonă'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='building_type',
            field=models.CharField(choices=[('Bloc de apartamente', 'Bloc de apartamente'), ('Bloc de garsoniere', 'Bloc de garsoniere'), ('Bloc mixt', 'Bloc mixt'), ('Vilă de apartamente', 'Vilă de apartamente'), ('Case / Vile', 'Case / Vile')], verbose_name='Tip imobil'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='construction_status',
            field=models.CharField(choices=[('Finalizată', 'Finalizată'), ('La gri', 'La gri'), ('La roșu', 'La roșu'), ('Structură', 'Structură'), ('Proiect', 'Proiect'), ('În construcție', 'În construcție'), ('De demolat', 'De demolat')], verbose_name='Stadiu construcție'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='construction_year',
            field=models.IntegerField(verbose_name='Anul construcției'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='interior_finishes',
            field=models.CharField(choices=[('Finisat modern', 'Finisat modern'), ('Finisat', 'Finisat'), ('Finisat clasic', 'Finisat clasic'), ('Semifinisat', 'Semifinisat'), ('Necesită renovare', 'Necesită renovare'), ('Nefinisat', 'Nefinisat')], verbose_name='Stare interior'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='nr_floors',
            field=models.IntegerField(verbose_name='Număr etaje'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Incompletă', 'Incompletă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Incompletă', verbose_name='Status proprietate'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='street_address',
            field=models.CharField(max_length=40, verbose_name='Stradă'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='street_nr',
            field=models.IntegerField(verbose_name='Număr stradă'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='zone',
            field=models.CharField(max_length=20, verbose_name='Zonă'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='classification',
            field=models.CharField(choices=[('Intravilan', 'Intravilan'), ('Extravilan', 'Extravilan')], verbose_name='Clasificare'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preț tranzacționare'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Incompletă', 'Incompletă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Incompletă', verbose_name='Status proprietate'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='street_address',
            field=models.CharField(max_length=40, verbose_name='Stradă'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='street_nr',
            field=models.IntegerField(verbose_name='Număr stradă'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='terrain_surface',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Suprafață teren'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='terrain_type',
            field=models.CharField(choices=[('Construcții', 'Construcții'), ('Agricol', 'Agricol'), ('Pădure', 'Pădure')], verbose_name='Tip teren'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='transaction_type',
            field=models.CharField(choices=[('Vânzare', 'Vânzare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='unit',
            field=models.CharField(choices=[('mp', 'mp'), ('ar', 'ar'), ('ha', 'ha')], verbose_name='Unitate suprafață'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='zone',
            field=models.CharField(max_length=20, verbose_name='Zonă'),
        ),
    ]
