# Generated by Django 5.0.3 on 2024-03-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_apartment_ap_compart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='property_type',
            field=models.CharField(choices=[('Apartament', 'Apartament'), ('Casă', 'Casă'), ('Teren', 'Teren'), ('Spațiu comercial', 'Spațiu comercial'), ('Spațiu de birouri', 'Spațiu de birouri'), ('Spațiu industrial', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='property_type',
            field=models.CharField(choices=[('Apartament', 'Apartament'), ('Casă', 'Casă'), ('Teren', 'Teren'), ('Spațiu comercial', 'Spațiu comercial'), ('Spațiu de birouri', 'Spațiu de birouri'), ('Spațiu industrial', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate'),
        ),
        migrations.AlterField(
            model_name='house',
            name='property_type',
            field=models.CharField(choices=[('Apartament', 'Apartament'), ('Casă', 'Casă'), ('Teren', 'Teren'), ('Spațiu comercial', 'Spațiu comercial'), ('Spațiu de birouri', 'Spațiu de birouri'), ('Spațiu industrial', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='property_type',
            field=models.CharField(choices=[('Apartament', 'Apartament'), ('Casă', 'Casă'), ('Teren', 'Teren'), ('Spațiu comercial', 'Spațiu comercial'), ('Spațiu de birouri', 'Spațiu de birouri'), ('Spațiu industrial', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='property_type',
            field=models.CharField(choices=[('Apartament', 'Apartament'), ('Casă', 'Casă'), ('Teren', 'Teren'), ('Spațiu comercial', 'Spațiu comercial'), ('Spațiu de birouri', 'Spațiu de birouri'), ('Spațiu industrial', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='property_type',
            field=models.CharField(choices=[('Apartament', 'Apartament'), ('Casă', 'Casă'), ('Teren', 'Teren'), ('Spațiu comercial', 'Spațiu comercial'), ('Spațiu de birouri', 'Spațiu de birouri'), ('Spațiu industrial', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate'),
        ),
    ]
