# Generated by Django 5.0.2 on 2024-03-01 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('listings', '0002_apartment_commercialspace_house_industrialspace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='owner_phone',
        ),
        migrations.RemoveField(
            model_name='commercialspace',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='commercialspace',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='commercialspace',
            name='owner_phone',
        ),
        migrations.RemoveField(
            model_name='house',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='house',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='house',
            name='owner_phone',
        ),
        migrations.RemoveField(
            model_name='industrialspace',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='industrialspace',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='industrialspace',
            name='owner_phone',
        ),
        migrations.RemoveField(
            model_name='officespace',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='officespace',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='officespace',
            name='owner_phone',
        ),
        migrations.RemoveField(
            model_name='terrain',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='terrain',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='terrain',
            name='owner_phone',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contact asociat'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contact asociat'),
        ),
        migrations.AlterField(
            model_name='house',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contact asociat'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contact asociat'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contact asociat'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contact asociat'),
        ),
    ]
