# Generated by Django 5.0.4 on 2024-06-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_apartment_floor_alter_commercialspace_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialspace',
            name='space_type',
            field=models.CharField(choices=[('Bloc de apartamente', 'Bloc de apartamente'), ('Clădire de birouri', 'Clădire de birouri'), ('Casă / Vilă', 'Casă / Vilă'), ('Centru comercial', 'Centru comercial'), ('Hală / Depozit', 'Hală / Depozit'), ('Stradal', 'Stradal')], verbose_name='Tip imobil'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='space_type',
            field=models.CharField(choices=[('Bloc de apartamente', 'Bloc de apartamente'), ('Clădire de birouri', 'Clădire de birouri'), ('Casă / Vilă', 'Casă / Vilă'), ('Centru comercial', 'Centru comercial'), ('Hală / Depozit', 'Hală / Depozit'), ('Stradal', 'Stradal')], verbose_name='Tip imobil'),
        ),
    ]
