# Generated by Django 5.0.2 on 2024-03-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_apartment_owner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', max_length=18, verbose_name='Tip proprietate⋆'),
        ),
        migrations.AddField(
            model_name='commercialspace',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', max_length=18, verbose_name='Tip proprietate⋆'),
        ),
        migrations.AddField(
            model_name='house',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', max_length=18, verbose_name='Tip proprietate⋆'),
        ),
        migrations.AddField(
            model_name='industrialspace',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', max_length=18, verbose_name='Tip proprietate⋆'),
        ),
        migrations.AddField(
            model_name='officespace',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', max_length=18, verbose_name='Tip proprietate⋆'),
        ),
        migrations.AddField(
            model_name='terrain',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', max_length=18, verbose_name='Tip proprietate⋆'),
        ),
    ]
