# Generated by Django 5.0.3 on 2024-03-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_apartment_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], max_length=20, verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], max_length=20, verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='house',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], max_length=20, verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], max_length=20, verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], max_length=20, verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], max_length=20, verbose_name='Județ⋆'),
        ),
    ]
