# Generated by Django 5.0.3 on 2024-03-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_apartment_county_alter_commercialspace_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officebuilding',
            name='developer_email',
        ),
        migrations.RemoveField(
            model_name='officebuilding',
            name='developer_name',
        ),
        migrations.RemoveField(
            model_name='officebuilding',
            name='developer_phone',
        ),
        migrations.RemoveField(
            model_name='residentialensemble',
            name='developer_email',
        ),
        migrations.RemoveField(
            model_name='residentialensemble',
            name='developer_name',
        ),
        migrations.RemoveField(
            model_name='residentialensemble',
            name='developer_phone',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='VAT_rate',
            field=models.CharField(blank=True, choices=[('Nu se aplică TVA', 'Nu se aplică TVA'), ('TVA inclus', 'TVA inclus'), ('+ 9% TVA', '+ 9% TVA'), ('+ 19% TVA', '+ 19% TVA')], default='Nu se aplică TVA', null=True, verbose_name='TVA'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='ap_compart',
            field=models.CharField(choices=[('Decomandat', 'Decomandat'), ('Semidecomandat', 'Semidecomandat'), ('Nedecomandat', 'Nedecomandat'), ('Circular', 'Circular'), ('Vagon', 'Vagon')], verbose_name='Compartimentare⋆'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartment_type',
            field=models.CharField(choices=[('Apartament', 'Apartament'), ('Garsonieră', 'Garsonieră'), ('Penthouse', 'Penthouse')], verbose_name='Tip apartament⋆'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='building_facilities',
            field=models.CharField(blank=True, choices=[('Acces persoane cu dizabilități', 'Acces persoane cu dizabilități'), ('Acoperiș', 'Acoperiș'), ('Interfon', 'Interfon'), ('Parcare biciclete', 'Parcare biciclete'), ('Pază', 'Pază'), ('Piscină', 'Piscină'), ('Spălătorie', 'Spălătorie'), ('Spații agrement', 'Spații agrement'), ('Supraveghere video', 'Supraveghere video'), ('Telecomandă poartă acces auto', 'Telecomandă poartă acces auto'), ('Telecomandă poartă garaj', 'Telecomandă poartă garaj'), ('Uscătorie', 'Uscătorie'), ('Videointerfon', 'Videointerfon')], null=True, verbose_name='Dotări imobil'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='building_type',
            field=models.CharField(blank=True, choices=[('Bloc de apartamente', 'Bloc de apartamente'), ('Bloc de garsoniere', 'Bloc de garsoniere'), ('Bloc mixt', 'Bloc mixt'), ('Vilă de apartamente', 'Vilă de apartamente')], null=True, verbose_name='Tip imobil'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='comfort',
            field=models.CharField(blank=True, choices=[('Lux', 'Lux'), ('1', '1'), ('2', '2'), ('3', '3')], null=True, verbose_name='Confort'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='construction_materials',
            field=models.CharField(blank=True, choices=[('Beton', 'Beton'), ('Cărămidă', 'Cărămidă'), ('BCA', 'BCA'), ('Metal', 'Metal'), ('Lemn', 'Lemn'), ('Altele', 'Altele'), ('Cadre', 'Cadre'), ('Plăci', 'Plăci'), ('Monolit', 'Monolit')], null=True, verbose_name='Materiale construcție'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='construction_status',
            field=models.CharField(blank=True, choices=[('Finalizată', 'Finalizată'), ('La gri', 'La gri'), ('La roșu', 'La roșu'), ('Structură', 'Structură'), ('Proiect', 'Proiect'), ('În construcție', 'În construcție'), ('De demolat', 'De demolat')], null=True, verbose_name='Stadiu construcție'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='currency',
            field=models.CharField(blank=True, choices=[('euro', '€'), ('lei', 'RON')], default='euro', null=True, verbose_name='Monedă'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='destination',
            field=models.CharField(blank=True, choices=[('Rezidențială', 'Rezidențială'), ('Comercială', 'Comercială'), ('Birouri', 'Birouri')], null=True, verbose_name='Destinație'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='entrance_door',
            field=models.CharField(blank=True, choices=[('Ușă intrare lemn', 'Ușă intrare lemn'), ('Ușă intrare metal', 'Ușă intrare metal'), ('Ușă intrare pal', 'Ușă intrare pal'), ('Ușă intrare PVC', 'Ușă intrare PVC')], null=True, verbose_name='Ușă intrare'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='facilities',
            field=models.CharField(blank=True, choices=[('Aer condiționat', 'Aer condiționat'), ('Aeroterme', 'Aeroterme'), ('Dressing', 'Dressing'), ('Jacuzzi', 'Jacuzzi'), ('Scară interioară', 'Scară interioară'), ('Șemineu', 'Șemineu'), ('Sistem de alarmă', 'Sistem de alarmă')], null=True, verbose_name='Dotări'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.CharField(choices=[('Demisol', 'Demisol'), ('Parter', 'Parter'), ('Parter înalt', 'Parter înalt'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('Mansardă', 'Mansardă'), ('Ultimele 2 etaje', 'Ultimele 2 etaje')], verbose_name='Etaj⋆'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='furniture',
            field=models.CharField(blank=True, choices=[('Mobilat complet', 'Mobilat complet'), ('Mobilat lux', 'Mobilat lux'), ('Mobilat parțial', 'Mobilat parțial'), ('Nemobilat', 'Nemobilat')], null=True, verbose_name='Mobilier'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='heating_system',
            field=models.CharField(blank=True, choices=[('Calorifere', 'Calorifere'), ('Centrală cu lemne', 'Centrală cu lemne'), ('Centrală cu peleți', 'Centrală cu peleți'), ('Centrală imobil', 'Centrală imobil'), ('Centrală proprie', 'Centrală proprie'), ('Încălzire diesel', 'Încălzire diesel'), ('Încălzire în pardoseală', 'Încălzire în pardoseală'), ('Pompă de căldură', 'Pompă de căldură'), ('Sobă / Teracotă', 'Sobă / Teracotă'), ('Termoficare', 'Termoficare'), ('Ventiloconvectoare', 'Ventiloconvectoare')], null=True, verbose_name='Sistem încălzire'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='interior_doors',
            field=models.CharField(blank=True, choices=[('Uși interior celulare', 'Uși interior celulare'), ('Uși interior lemn', 'Uși interior lemn'), ('Uși interior MDF', 'Uși interior MDF'), ('Uși interior cu panel', 'Uși interior cu panel'), ('Uși interior PVC', 'Uși interior PVC'), ('Uși interior sticlă', 'Uși interior sticlă')], null=True, verbose_name='Uși interior'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='interior_finishes',
            field=models.CharField(choices=[('Finisat modern', 'Finisat modern'), ('Finisat', 'Finisat'), ('Finisat clasic', 'Finisat clasic'), ('Semifinisat', 'Semifinisat'), ('Necesită renovare', 'Necesită renovare'), ('Nefinisat', 'Nefinisat')], verbose_name='Stare interior⋆'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='kitchen',
            field=models.CharField(blank=True, choices=[('Bucătărie deschisă', 'Bucătărie deschisă'), ('Bucătărie închisă', 'Bucătărie închisă'), ('Bucătărie mobilată', 'Bucătărie mobilată'), ('Bucătărie parțial mobilată', 'Bucătărie parțial mobilată'), ('Bucătărie parțial utilată', 'Bucătărie parțial utilată'), ('Bucătărie utilată', 'Bucătărie utilată'), ('Chicinetă', 'Chicinetă')], null=True, verbose_name='Bucătărie'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='orientation',
            field=models.CharField(blank=True, choices=[('Nord', 'Nord'), ('Sud', 'Sud'), ('Vest', 'Vest'), ('Est', 'Est'), ('Nord-Vest', 'Nord-Vest'), ('Nord-Est', 'Nord-Est'), ('Sud-Vest', 'Sud-Vest'), ('Sud-Est', 'Sud-Est'), ('Nord-Sud', 'Nord-Sud'), ('Vest-Est', 'Vest-Est')], null=True, verbose_name='Orientare'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='other_spaces',
            field=models.CharField(blank=True, choices=[('Grădină proprie', 'Grădină proprie'), ('Boxă la subsol', 'Boxă la subsol'), ('Curte', 'Curte'), ('Curte comună', 'Curte comună'), ('Debara', 'Debara'), ('Lift', 'Lift'), ('Loc de joacă copii', 'Loc de joacă copii'), ('Magazie', 'Magazie'), ('Pivniță', 'Pivniță'), ('Zonă barbeque', 'Zonă barbeque')], null=True, verbose_name='Alte spații'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='owner_type',
            field=models.CharField(blank=True, choices=[('Persoană fizică', 'Persoană fizică'), ('Persoană juridică', 'Persoană juridică')], null=True, verbose_name='Tip proprietar'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='parking',
            field=models.CharField(blank=True, choices=[('Garaj', 'Garaj'), ('Garaj subteran', 'Garaj subteran'), ('Parcare acoperită', 'Parcare acoperită'), ('Parcare deschisă', 'Parcare deschisă')], null=True, verbose_name='Parcare'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit ipotecar', 'Credit ipotecar'), ('Credit Prima Casă', 'Credit Prima Casă'), ('Rate la dezvoltator', 'Rate la dezvoltator')], null=True, verbose_name='Modalitate plată acceptată'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Incompletă', 'Incompletă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Incompletă', verbose_name='Status proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='thermal_insulation',
            field=models.CharField(blank=True, choices=[('Izolație exterioară', 'Izolație exterioară'), ('Izolație interioară', 'Izolație interioară')], null=True, verbose_name='Izolație termică'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='transaction_type',
            field=models.CharField(choices=[('Vânzare', 'Vânzare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție⋆'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='windows',
            field=models.CharField(blank=True, choices=[('Ferestre aluminiu', 'Ferestre aluminiu'), ('Ferestre lemn', 'Ferestre lemn'), ('Ferestre PVC', 'Ferestre PVC'), ('Geamuri cu izolație fonică', 'Geamuri cu izolație fonică'), ('Geamuri cu protecție UV', 'Geamuri cu protecție UV'), ('Geamuri termopan', 'Geamuri termopan'), ('Geamuri tripan', 'Geamuri tripan')], null=True, verbose_name='Ferestre'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='VAT_rate',
            field=models.CharField(blank=True, choices=[('Nu se aplică TVA', 'Nu se aplică TVA'), ('TVA inclus', 'TVA inclus'), ('+ 9% TVA', '+ 9% TVA'), ('+ 19% TVA', '+ 19% TVA')], default='Nu se aplică TVA', null=True, verbose_name='TVA'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='currency',
            field=models.CharField(blank=True, choices=[('euro', '€'), ('lei', 'RON')], default='euro', null=True, verbose_name='Monedă'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='destination',
            field=models.CharField(blank=True, choices=[('Comercială', 'Comercială'), ('Birouri', 'Birouri'), ('Horeca / Retail', 'Horeca / Retail'), ('Magazin prezentare', 'Magazin prezentare'), ('Showroom', 'Showroom'), ('Bancă', 'Bancă'), ('Farmacie', 'Farmacie')], null=True, verbose_name='Destinație'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='eco_elements',
            field=models.CharField(blank=True, choices=[('Building management system', 'Building management system'), ('Certificare Green Building', 'Certificare Green Building'), ('Echipamente moderne / silențioase', 'Echipamente moderne / silențioase'), ('Fațadă ventilată', 'Fațadă ventilată'), ('Incărcător auto electrice', 'Incărcător auto electrice'), ('Panouri solare', 'Panouri solare'), ('Parcare biciclete', 'Parcare biciclete'), ('Sistem electric inteligent', 'Sistem electric inteligent'), ('Sistem inteligent ascensoare', 'Sistem inteligent ascensoare')], null=True, verbose_name='Elemente ECO'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='floor',
            field=models.CharField(choices=[('Demisol', 'Demisol'), ('Parter', 'Parter'), ('Parter înalt', 'Parter înalt'), ('Mezanin', 'Mezanin'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('Mansardă', 'Mansardă'), ('Ultimele 2 etaje', 'Ultimele 2 etaje')], verbose_name='Etaj⋆'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='land_facilities',
            field=models.CharField(blank=True, choices=[('Apă', 'Apă'), ('Canalizare', 'Canalizare'), ('Curent', 'Curent'), ('Gaz', 'Gaz'), ('Irigații', 'Irigații'), ('Utilități în zonă', 'Utilități în zonă')], null=True, verbose_name='Facilități teren'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='other_facilities_com_sp',
            field=models.CharField(blank=True, choices=[('Acces persoane cu dizabilități', 'Acces persoane cu dizabilități'), ('Acces secundar marfă', 'Acces secundar marfă'), ('Afișare logo pe clădire', 'Afișare logo pe clădire'), ('Centrală termică', 'Centrală termică'), ('Contorizare separată', 'Contorizare separată'), ('Grupuri sanitare amenajate și utilate', 'Grupuri sanitare amenajate și utilate'), ('Posibilitate terasă', 'Posibilitate terasă'), ('Sistem de alarmă', 'Sistem de alarmă'), ('Sistem de ventilație', 'Sistem de ventilație'), ('Vestiar', 'Vestiar')], null=True, verbose_name='Alte facilități'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='owner_type',
            field=models.CharField(blank=True, choices=[('Persoană fizică', 'Persoană fizică'), ('Persoană juridică', 'Persoană juridică')], null=True, verbose_name='Tip proprietar'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='parking',
            field=models.CharField(blank=True, choices=[('Garaj', 'Garaj'), ('Garaj subteran', 'Garaj subteran'), ('Parcare acoperită', 'Parcare acoperită'), ('Parcare deschisă', 'Parcare deschisă')], null=True, verbose_name='Parcare'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit ipotecar', 'Credit ipotecar'), ('Credit Prima Casă', 'Credit Prima Casă'), ('Rate la dezvoltator', 'Rate la dezvoltator')], null=True, verbose_name='Modalitate plată acceptată'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='pedestrian_traffic',
            field=models.CharField(blank=True, choices=[('Intens', 'Intens'), ('Moderat', 'Moderat'), ('Fără trafic pietonal', 'Fără trafic pietonal')], null=True, verbose_name='Trafic pietonal'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='space_compart',
            field=models.CharField(blank=True, choices=[('Open-space', 'Open-space'), ('Compartimentat', 'Compartimentat'), ('Parțial compartimentat', 'Parțial compartimentat'), ('Flexibil', 'Flexibil')], null=True, verbose_name='Compartimentare'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='space_type',
            field=models.CharField(choices=[('Bloc de apartamente', 'Bloc de apartamente'), ('Clădire birouri', 'Clădire birouri'), ('Casă / Vilă', 'Casă / Vilă'), ('Centru comercial', 'Centru comercial'), ('Hală / Depozit', 'Hală / Depozit'), ('Stradal', 'Stradal')], verbose_name='Tip imobil⋆'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Incompletă', 'Incompletă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Incompletă', verbose_name='Status proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='transaction_type',
            field=models.CharField(choices=[('Vânzare', 'Vânzare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție⋆'),
        ),
        migrations.AlterField(
            model_name='house',
            name='VAT_rate',
            field=models.CharField(blank=True, choices=[('Nu se aplică TVA', 'Nu se aplică TVA'), ('TVA inclus', 'TVA inclus'), ('+ 9% TVA', '+ 9% TVA'), ('+ 19% TVA', '+ 19% TVA')], default='Nu se aplică TVA', null=True, verbose_name='TVA'),
        ),
        migrations.AlterField(
            model_name='house',
            name='building_facilities',
            field=models.CharField(blank=True, choices=[('Acces persoane cu dizabilități', 'Acces persoane cu dizabilități'), ('Acoperiș', 'Acoperiș'), ('Interfon', 'Interfon'), ('Parcare biciclete', 'Parcare biciclete'), ('Pază', 'Pază'), ('Piscină', 'Piscină'), ('Spălătorie', 'Spălătorie'), ('Spații agrement', 'Spații agrement'), ('Supraveghere video', 'Supraveghere video'), ('Telecomandă poartă acces auto', 'Telecomandă poartă acces auto'), ('Telecomandă poartă garaj', 'Telecomandă poartă garaj'), ('Uscătorie', 'Uscătorie'), ('Videointerfon', 'Videointerfon')], null=True, verbose_name='Dotări imobil'),
        ),
        migrations.AlterField(
            model_name='house',
            name='construction_materials',
            field=models.CharField(blank=True, choices=[('Beton', 'Beton'), ('Cărămidă', 'Cărămidă'), ('BCA', 'BCA'), ('Metal', 'Metal'), ('Lemn', 'Lemn'), ('Altele', 'Altele'), ('Cadre', 'Cadre'), ('Plăci', 'Plăci'), ('Monolit', 'Monolit')], null=True, verbose_name='Materiale construcție'),
        ),
        migrations.AlterField(
            model_name='house',
            name='construction_status',
            field=models.CharField(blank=True, choices=[('Finalizată', 'Finalizată'), ('La gri', 'La gri'), ('La roșu', 'La roșu'), ('Structură', 'Structură'), ('Proiect', 'Proiect'), ('În construcție', 'În construcție'), ('De demolat', 'De demolat')], null=True, verbose_name='Stadiu construcție'),
        ),
        migrations.AlterField(
            model_name='house',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='house',
            name='currency',
            field=models.CharField(blank=True, choices=[('euro', '€'), ('lei', 'RON')], default='euro', null=True, verbose_name='Monedă'),
        ),
        migrations.AlterField(
            model_name='house',
            name='destination',
            field=models.CharField(blank=True, choices=[('Rezidențială', 'Rezidențială'), ('Comercială', 'Comercială'), ('Birouri', 'Birouri')], null=True, verbose_name='Destinație'),
        ),
        migrations.AlterField(
            model_name='house',
            name='entrance_door',
            field=models.CharField(blank=True, choices=[('Ușă intrare lemn', 'Ușă intrare lemn'), ('Ușă intrare metal', 'Ușă intrare metal'), ('Ușă intrare pal', 'Ușă intrare pal'), ('Ușă intrare PVC', 'Ușă intrare PVC')], null=True, verbose_name='Ușă intrare'),
        ),
        migrations.AlterField(
            model_name='house',
            name='facilities',
            field=models.CharField(blank=True, choices=[('Aer condiționat', 'Aer condiționat'), ('Aeroterme', 'Aeroterme'), ('Dressing', 'Dressing'), ('Jacuzzi', 'Jacuzzi'), ('Scară interioară', 'Scară interioară'), ('Șemineu', 'Șemineu'), ('Sistem de alarmă', 'Sistem de alarmă')], null=True, verbose_name='Dotări'),
        ),
        migrations.AlterField(
            model_name='house',
            name='furniture',
            field=models.CharField(blank=True, choices=[('Mobilat complet', 'Mobilat complet'), ('Mobilat lux', 'Mobilat lux'), ('Mobilat parțial', 'Mobilat parțial'), ('Nemobilat', 'Nemobilat')], null=True, verbose_name='Mobilier'),
        ),
        migrations.AlterField(
            model_name='house',
            name='heating_system',
            field=models.CharField(blank=True, choices=[('Calorifere', 'Calorifere'), ('Centrală cu lemne', 'Centrală cu lemne'), ('Centrală cu peleți', 'Centrală cu peleți'), ('Centrală imobil', 'Centrală imobil'), ('Centrală proprie', 'Centrală proprie'), ('Încălzire diesel', 'Încălzire diesel'), ('Încălzire în pardoseală', 'Încălzire în pardoseală'), ('Pompă de căldură', 'Pompă de căldură'), ('Sobă / Teracotă', 'Sobă / Teracotă'), ('Termoficare', 'Termoficare'), ('Ventiloconvectoare', 'Ventiloconvectoare')], null=True, verbose_name='Sistem încălzire'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('Individuală', 'Individuală'), ('Vilă', 'Vilă'), ('Calcan', 'Calcan'), ('Duplex', 'Duplex'), ('Triplex', 'Triplex'), ('Înșiruită', 'Înșiruită')], verbose_name='Tip casă⋆'),
        ),
        migrations.AlterField(
            model_name='house',
            name='interior_doors',
            field=models.CharField(blank=True, choices=[('Uși interior celulare', 'Uși interior celulare'), ('Uși interior lemn', 'Uși interior lemn'), ('Uși interior MDF', 'Uși interior MDF'), ('Uși interior cu panel', 'Uși interior cu panel'), ('Uși interior PVC', 'Uși interior PVC'), ('Uși interior sticlă', 'Uși interior sticlă')], null=True, verbose_name='Uși interior'),
        ),
        migrations.AlterField(
            model_name='house',
            name='interior_finishes',
            field=models.CharField(choices=[('Finisat modern', 'Finisat modern'), ('Finisat', 'Finisat'), ('Finisat clasic', 'Finisat clasic'), ('Semifinisat', 'Semifinisat'), ('Necesită renovare', 'Necesită renovare'), ('Nefinisat', 'Nefinisat')], verbose_name='Stare interior⋆'),
        ),
        migrations.AlterField(
            model_name='house',
            name='kitchen',
            field=models.CharField(blank=True, choices=[('Bucătărie deschisă', 'Bucătărie deschisă'), ('Bucătărie închisă', 'Bucătărie închisă'), ('Bucătărie mobilată', 'Bucătărie mobilată'), ('Bucătărie parțial mobilată', 'Bucătărie parțial mobilată'), ('Bucătărie parțial utilată', 'Bucătărie parțial utilată'), ('Bucătărie utilată', 'Bucătărie utilată'), ('Chicinetă', 'Chicinetă')], null=True, verbose_name='Bucătărie'),
        ),
        migrations.AlterField(
            model_name='house',
            name='other_spaces',
            field=models.CharField(blank=True, choices=[('Grădină proprie', 'Grădină proprie'), ('Boxă la subsol', 'Boxă la subsol'), ('Curte', 'Curte'), ('Curte comună', 'Curte comună'), ('Debara', 'Debara'), ('Lift', 'Lift'), ('Loc de joacă copii', 'Loc de joacă copii'), ('Magazie', 'Magazie'), ('Pivniță', 'Pivniță'), ('Zonă barbeque', 'Zonă barbeque')], null=True, verbose_name='Alte spații'),
        ),
        migrations.AlterField(
            model_name='house',
            name='owner_type',
            field=models.CharField(blank=True, choices=[('Persoană fizică', 'Persoană fizică'), ('Persoană juridică', 'Persoană juridică')], null=True, verbose_name='Tip proprietar'),
        ),
        migrations.AlterField(
            model_name='house',
            name='parking',
            field=models.CharField(blank=True, choices=[('Garaj', 'Garaj'), ('Garaj subteran', 'Garaj subteran'), ('Parcare acoperită', 'Parcare acoperită'), ('Parcare deschisă', 'Parcare deschisă')], null=True, verbose_name='Parcare'),
        ),
        migrations.AlterField(
            model_name='house',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit ipotecar', 'Credit ipotecar'), ('Credit Prima Casă', 'Credit Prima Casă'), ('Rate la dezvoltator', 'Rate la dezvoltator')], null=True, verbose_name='Modalitate plată acceptată'),
        ),
        migrations.AlterField(
            model_name='house',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='house',
            name='roof',
            field=models.CharField(blank=True, choices=[('Tablă', 'Tablă'), ('Țiglă', 'Țiglă'), ('Șindrilă', 'Șindrilă'), ('Terasă', 'Terasă')], null=True, verbose_name='Acoperiș'),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Incompletă', 'Incompletă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Incompletă', verbose_name='Status proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='house',
            name='thermal_insulation',
            field=models.CharField(blank=True, choices=[('Izolație exterioară', 'Izolație exterioară'), ('Izolație interioară', 'Izolație interioară')], null=True, verbose_name='Izolație termică'),
        ),
        migrations.AlterField(
            model_name='house',
            name='transaction_type',
            field=models.CharField(choices=[('Vânzare', 'Vânzare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție⋆'),
        ),
        migrations.AlterField(
            model_name='house',
            name='windows',
            field=models.CharField(blank=True, choices=[('Ferestre aluminiu', 'Ferestre aluminiu'), ('Ferestre lemn', 'Ferestre lemn'), ('Ferestre PVC', 'Ferestre PVC'), ('Geamuri cu izolație fonică', 'Geamuri cu izolație fonică'), ('Geamuri cu protecție UV', 'Geamuri cu protecție UV'), ('Geamuri termopan', 'Geamuri termopan'), ('Geamuri tripan', 'Geamuri tripan')], null=True, verbose_name='Ferestre'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='VAT_rate',
            field=models.CharField(blank=True, choices=[('Nu se aplică TVA', 'Nu se aplică TVA'), ('TVA inclus', 'TVA inclus'), ('+ 9% TVA', '+ 9% TVA'), ('+ 19% TVA', '+ 19% TVA')], default='Nu se aplică TVA', null=True, verbose_name='TVA'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='currency',
            field=models.CharField(blank=True, choices=[('euro', '€'), ('lei', 'RON')], default='euro', null=True, verbose_name='Monedă'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='destination',
            field=models.CharField(blank=True, choices=[('Producție', 'Producție'), ('Depozitare', 'Depozitare'), ('Prezentare', 'Prezentare')], null=True, verbose_name='Destinație'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='floor',
            field=models.CharField(blank=True, choices=[('Demisol', 'Demisol'), ('Parter', 'Parter'), ('Parter înalt', 'Parter înalt'), ('1', '1'), ('2', '2'), ('3', '3'), ('Mansardă', 'Mansardă')], null=True, verbose_name='Etaj'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='land_facilities',
            field=models.CharField(blank=True, choices=[('Apă', 'Apă'), ('Canalizare', 'Canalizare'), ('Curent', 'Curent'), ('Gaz', 'Gaz'), ('Irigații', 'Irigații'), ('Utilități în zonă', 'Utilități în zonă')], null=True, verbose_name='Facilități teren'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='other_facilities_ind_sp',
            field=models.CharField(blank=True, choices=[('Acces auto', 'Acces auto'), ('Acces camion', 'Acces camion'), ('Construcție demolabilă', 'Construcție demolabilă'), ('Curent trifazic (380V)', 'Curent trifazic (380V)'), ('La șosea', 'La șosea'), ('Luminatoare', 'Luminatoare'), ('Oportunitate de investiții', 'Oportunitate de investiții'), ('Panouri solare', 'Panouri solare'), ('Pod rulant', 'Pod rulant'), ('Posibilitate de compartimentare', 'Posibilitate de compartimentare'), ('Sistem de alarmă', 'Sistem de alarmă'), ('Teren împrejmuit', 'Teren împrejmuit'), ('Uși de acces', 'Uși de acces'), ('Vestiar', 'Vestiar')], null=True, verbose_name='Alte facilități spațiu industrial'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='owner_type',
            field=models.CharField(blank=True, choices=[('Persoană fizică', 'Persoană fizică'), ('Persoană juridică', 'Persoană juridică')], null=True, verbose_name='Tip proprietar'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='parking',
            field=models.CharField(blank=True, choices=[('Garaj', 'Garaj'), ('Garaj subteran', 'Garaj subteran'), ('Parcare acoperită', 'Parcare acoperită'), ('Parcare deschisă', 'Parcare deschisă')], null=True, verbose_name='Parcare'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit ipotecar', 'Credit ipotecar'), ('Credit Prima Casă', 'Credit Prima Casă'), ('Rate la dezvoltator', 'Rate la dezvoltator')], null=True, verbose_name='Modalitate plată acceptată'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='space_class',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], null=True, verbose_name='Clasă birouri'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='space_compart',
            field=models.CharField(blank=True, choices=[('Open-space', 'Open-space'), ('Compartimentat', 'Compartimentat'), ('Parțial compartimentat', 'Parțial compartimentat'), ('Flexibil', 'Flexibil')], null=True, verbose_name='Compartimentare'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='space_type',
            field=models.CharField(choices=[('Producție grea', 'Producție grea'), ('Producție ușoară', 'Producție ușoară'), ('Depozit distribuție', 'Depozit distribuție'), ('Depozit general', 'Depozit general'), ('Cercetare și dezvoltare', 'Cercetare și dezvoltare'), ('Centru de date', 'Centru de date'), ('Showroom', 'Showroom')], verbose_name='Tip spațiu⋆'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Incompletă', 'Incompletă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Incompletă', verbose_name='Status proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='industrialspace',
            name='transaction_type',
            field=models.CharField(choices=[('Vânzare', 'Vânzare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție⋆'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='air_conditioning',
            field=models.CharField(blank=True, choices=[('Aport de aer proaspăt', 'Aport de aer proaspăt'), ('Centrală termică', 'Centrală termică'), ('Control individual AC pentru fiecare zonă de birou', 'Control individual AC pentru fiecare zonă de birou'), ('Sistem climatizare 2 țevi', 'Sistem climatizare 2 țevi'), ('Sistem climatizare 4 țevi', 'Sistem climatizare 4 țevi'), ('Unități Split', 'Unități Split'), ('Ventilație mecanică', 'Ventilație mecanică')], null=True, verbose_name='Climatizare birou'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='architecture',
            field=models.CharField(blank=True, choices=[('Cortină de sticlă', 'Cortină de sticlă'), ('Ferestre care se deschid', 'Ferestre care se deschid'), ('Ferestre înclinate', 'Ferestre înclinate'), ('Gresie', 'Gresie'), ('Grupuri sanitare amenajate și utilate', 'Grupuri sanitare amenajate și utilate'), ('Lift cu destinație programată', 'Lift cu destinație programată'), ('Mochetă', 'Mochetă'), ('Parchet', 'Parchet'), ('Podea înălțată', 'Podea înălțată'), ('Post trafo', 'Post trafo'), ('Tavan fals', 'Tavan fals')], null=True, verbose_name='Arhitectură'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='building_facilities_proximity',
            field=models.CharField(blank=True, choices=[('Stație de autobuz în apropiere', 'Stație de autobuz în apropiere'), ('Cafenea la parter', 'Cafenea la parter'), ('Centru comercial în apropiere', 'Centru comercial în apropiere'), ('Restaurant în clădire', 'Restaurant în clădire'), ('Stație de metrou în apropiere', 'Stație de metrou în apropiere'), ('Stație de tramvai în apropiere', 'Stație de tramvai în apropiere')], null=True, verbose_name='Facilități clădire / proximități'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='construction_materials',
            field=models.CharField(blank=True, choices=[('Beton', 'Beton'), ('Cărămidă', 'Cărămidă'), ('BCA', 'BCA'), ('Metal', 'Metal'), ('Lemn', 'Lemn'), ('Altele', 'Altele'), ('Cadre', 'Cadre'), ('Plăci', 'Plăci'), ('Monolit', 'Monolit')], null=True, verbose_name='Materiale construcție'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='construction_status',
            field=models.CharField(choices=[('Finalizată', 'Finalizată'), ('La gri', 'La gri'), ('La roșu', 'La roșu'), ('Structură', 'Structură'), ('Proiect', 'Proiect'), ('În construcție', 'În construcție'), ('De demolat', 'De demolat')], verbose_name='Stadiu construcție⋆'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='eco_elements',
            field=models.CharField(blank=True, choices=[('Building management system', 'Building management system'), ('Certificare Green Building', 'Certificare Green Building'), ('Echipamente moderne / silențioase', 'Echipamente moderne / silențioase'), ('Fațadă ventilată', 'Fațadă ventilată'), ('Incărcător auto electrice', 'Incărcător auto electrice'), ('Panouri solare', 'Panouri solare'), ('Parcare biciclete', 'Parcare biciclete'), ('Sistem electric inteligent', 'Sistem electric inteligent'), ('Sistem inteligent ascensoare', 'Sistem inteligent ascensoare')], null=True, verbose_name='Elemente ECO'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='electrical_system',
            field=models.CharField(blank=True, choices=[('Control electric individual pe zona de birou', 'Control electric individual pe zona de birou'), ('Generator de urgență', 'Generator de urgență'), ('Necesită surse suplimentare de energie', 'Necesită surse suplimentare de energie'), ('Sursă principală de alimentare', 'Sursă principală de alimentare'), ('Sursa UPS', 'Sursa UPS')], null=True, verbose_name='Sistem electric'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='interior_finishes',
            field=models.CharField(choices=[('Finisat modern', 'Finisat modern'), ('Finisat', 'Finisat'), ('Finisat clasic', 'Finisat clasic'), ('Semifinisat', 'Semifinisat'), ('Necesită renovare', 'Necesită renovare'), ('Nefinisat', 'Nefinisat')], verbose_name='Stare interior⋆'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='it_c',
            field=models.CharField(blank=True, choices=[('Internet', 'Internet'), ('Posibilitatea alegerii operator date', 'Posibilitatea alegerii operator date'), ('Posibilitatea alegerii operator telefonie', 'Posibilitatea alegerii operator telefonie'), ('Sistem modern de telecomunicații', 'Sistem modern de telecomunicații'), ('Telefon', 'Telefon')], null=True, verbose_name='IT & C'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='safety_security',
            field=models.CharField(blank=True, choices=[('Acces securizat parcare', 'Acces securizat parcare'), ('Cameră server', 'Cameră server'), ('CCTV', 'CCTV'), ('Control acces securizat pe bază de cartele', 'Control acces securizat pe bază de cartele'), ('Control al accesului pe zone', 'Control al accesului pe zone'), ('Detectoare de fum / incendiu', 'Detectoare de fum / incendiu'), ('Extinctoare sprinkler', 'Extinctoare sprinkler'), ('Pază permanentă', 'Pază permanentă'), ('Recepție', 'Recepție'), ('Semaforizare parcare', 'Semaforizare parcare'), ('Server room cu rack, ventilație, control acces', 'Server room cu rack, ventilație, control acces'), ('Sistem de alarmă', 'Sistem de alarmă'), ('Sistem de evacuare', 'Sistem de evacuare'), ('Sisteme de securitate integrate BMS', 'Sisteme de securitate integrate BMS')], null=True, verbose_name='Siguranță și securitate'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='services_provided',
            field=models.CharField(blank=True, choices=[('Acces persoane cu dizabilități', 'Acces persoane cu dizabilități'), ('Administrare și management imobiliar', 'Administrare și management imobiliar'), ('Afișare logo pe clădire', 'Afișare logo pe clădire'), ('Consumabile grupuri sociale', 'Consumabile grupuri sociale'), ('Contorizare separată', 'Contorizare separată'), ('Curățenie exterioară', 'Curățenie exterioară'), ('Curățenie parcare', 'Curățenie parcare'), ('Curățenie spații comune', 'Curățenie spații comune'), ('Îndepărtarea zăpezii', 'Îndepărtarea zăpezii'), ('Îngrijirea spațiilor verzi', 'Îngrijirea spațiilor verzi'), ('Salubritate', 'Salubritate'), ('Servicii de întreținere și reparații lifturi', 'Servicii de întreținere și reparații lifturi'), ('Sistem de ventilație', 'Sistem de ventilație'), ('Vestiar', 'Vestiar')], null=True, verbose_name='Servicii asigurate'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='space_class',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], null=True, verbose_name='Clasă'),
        ),
        migrations.AlterField(
            model_name='officebuilding',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Incompletă', 'Incompletă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Incompletă', verbose_name='Status proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='VAT_rate',
            field=models.CharField(blank=True, choices=[('Nu se aplică TVA', 'Nu se aplică TVA'), ('TVA inclus', 'TVA inclus'), ('+ 9% TVA', '+ 9% TVA'), ('+ 19% TVA', '+ 19% TVA')], default='Nu se aplică TVA', null=True, verbose_name='TVA'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='air_conditioning',
            field=models.CharField(blank=True, choices=[('Aport de aer proaspăt', 'Aport de aer proaspăt'), ('Centrală termică', 'Centrală termică'), ('Control individual AC pentru fiecare zonă de birou', 'Control individual AC pentru fiecare zonă de birou'), ('Sistem climatizare 2 țevi', 'Sistem climatizare 2 țevi'), ('Sistem climatizare 4 țevi', 'Sistem climatizare 4 țevi'), ('Unități Split', 'Unități Split'), ('Ventilație mecanică', 'Ventilație mecanică')], null=True, verbose_name='Climatizare birou'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='architecture',
            field=models.CharField(blank=True, choices=[('Cortină de sticlă', 'Cortină de sticlă'), ('Ferestre care se deschid', 'Ferestre care se deschid'), ('Ferestre înclinate', 'Ferestre înclinate'), ('Gresie', 'Gresie'), ('Grupuri sanitare amenajate și utilate', 'Grupuri sanitare amenajate și utilate'), ('Lift cu destinație programată', 'Lift cu destinație programată'), ('Mochetă', 'Mochetă'), ('Parchet', 'Parchet'), ('Podea înălțată', 'Podea înălțată'), ('Post trafo', 'Post trafo'), ('Tavan fals', 'Tavan fals')], null=True, verbose_name='Arhitectură'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='building_facilities_proximity',
            field=models.CharField(blank=True, choices=[('Stație de autobuz în apropiere', 'Stație de autobuz în apropiere'), ('Cafenea la parter', 'Cafenea la parter'), ('Centru comercial în apropiere', 'Centru comercial în apropiere'), ('Restaurant în clădire', 'Restaurant în clădire'), ('Stație de metrou în apropiere', 'Stație de metrou în apropiere'), ('Stație de tramvai în apropiere', 'Stație de tramvai în apropiere')], null=True, verbose_name='Facilități clădire / proximități'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='currency',
            field=models.CharField(blank=True, choices=[('euro', '€'), ('lei', 'RON')], default='euro', null=True, verbose_name='Monedă'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='eco_elements',
            field=models.CharField(blank=True, choices=[('Building management system', 'Building management system'), ('Certificare Green Building', 'Certificare Green Building'), ('Echipamente moderne / silențioase', 'Echipamente moderne / silențioase'), ('Fațadă ventilată', 'Fațadă ventilată'), ('Incărcător auto electrice', 'Incărcător auto electrice'), ('Panouri solare', 'Panouri solare'), ('Parcare biciclete', 'Parcare biciclete'), ('Sistem electric inteligent', 'Sistem electric inteligent'), ('Sistem inteligent ascensoare', 'Sistem inteligent ascensoare')], null=True, verbose_name='Elemente ECO'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='electrical_system',
            field=models.CharField(blank=True, choices=[('Control electric individual pe zona de birou', 'Control electric individual pe zona de birou'), ('Generator de urgență', 'Generator de urgență'), ('Necesită surse suplimentare de energie', 'Necesită surse suplimentare de energie'), ('Sursă principală de alimentare', 'Sursă principală de alimentare'), ('Sursa UPS', 'Sursa UPS')], null=True, verbose_name='Sistem electric'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='floor',
            field=models.CharField(choices=[('Demisol', 'Demisol'), ('Parter', 'Parter'), ('Parter înalt', 'Parter înalt'), ('Mezanin', 'Mezanin'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('Mansardă', 'Mansardă'), ('Ultimele 2 etaje', 'Ultimele 2 etaje')], verbose_name='Etaj⋆'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='it_c',
            field=models.CharField(blank=True, choices=[('Internet', 'Internet'), ('Posibilitatea alegerii operator date', 'Posibilitatea alegerii operator date'), ('Posibilitatea alegerii operator telefonie', 'Posibilitatea alegerii operator telefonie'), ('Sistem modern de telecomunicații', 'Sistem modern de telecomunicații'), ('Telefon', 'Telefon')], null=True, verbose_name='IT & C'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='owner_type',
            field=models.CharField(blank=True, choices=[('Persoană fizică', 'Persoană fizică'), ('Persoană juridică', 'Persoană juridică')], null=True, verbose_name='Tip proprietar'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='parking',
            field=models.CharField(blank=True, choices=[('Garaj', 'Garaj'), ('Garaj subteran', 'Garaj subteran'), ('Parcare acoperită', 'Parcare acoperită'), ('Parcare deschisă', 'Parcare deschisă')], null=True, verbose_name='Parcare'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit ipotecar', 'Credit ipotecar'), ('Credit Prima Casă', 'Credit Prima Casă'), ('Rate la dezvoltator', 'Rate la dezvoltator')], null=True, verbose_name='Modalitate plată acceptată'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='safety_security',
            field=models.CharField(blank=True, choices=[('Acces securizat parcare', 'Acces securizat parcare'), ('Cameră server', 'Cameră server'), ('CCTV', 'CCTV'), ('Control acces securizat pe bază de cartele', 'Control acces securizat pe bază de cartele'), ('Control al accesului pe zone', 'Control al accesului pe zone'), ('Detectoare de fum / incendiu', 'Detectoare de fum / incendiu'), ('Extinctoare sprinkler', 'Extinctoare sprinkler'), ('Pază permanentă', 'Pază permanentă'), ('Recepție', 'Recepție'), ('Semaforizare parcare', 'Semaforizare parcare'), ('Server room cu rack, ventilație, control acces', 'Server room cu rack, ventilație, control acces'), ('Sistem de alarmă', 'Sistem de alarmă'), ('Sistem de evacuare', 'Sistem de evacuare'), ('Sisteme de securitate integrate BMS', 'Sisteme de securitate integrate BMS')], null=True, verbose_name='Siguranță și securitate'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='services_provided',
            field=models.CharField(blank=True, choices=[('Acces persoane cu dizabilități', 'Acces persoane cu dizabilități'), ('Administrare și management imobiliar', 'Administrare și management imobiliar'), ('Afișare logo pe clădire', 'Afișare logo pe clădire'), ('Consumabile grupuri sociale', 'Consumabile grupuri sociale'), ('Contorizare separată', 'Contorizare separată'), ('Curățenie exterioară', 'Curățenie exterioară'), ('Curățenie parcare', 'Curățenie parcare'), ('Curățenie spații comune', 'Curățenie spații comune'), ('Îndepărtarea zăpezii', 'Îndepărtarea zăpezii'), ('Îngrijirea spațiilor verzi', 'Îngrijirea spațiilor verzi'), ('Salubritate', 'Salubritate'), ('Servicii de întreținere și reparații lifturi', 'Servicii de întreținere și reparații lifturi'), ('Sistem de ventilație', 'Sistem de ventilație'), ('Vestiar', 'Vestiar')], null=True, verbose_name='Servicii asigurate'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='space_class',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], null=True, verbose_name='Clasă'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='space_compart',
            field=models.CharField(blank=True, choices=[('Open-space', 'Open-space'), ('Compartimentat', 'Compartimentat'), ('Parțial compartimentat', 'Parțial compartimentat'), ('Flexibil', 'Flexibil')], null=True, verbose_name='Compartimentare'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='space_type',
            field=models.CharField(choices=[('Bloc de apartamente', 'Bloc de apartamente'), ('Clădire birouri', 'Clădire birouri'), ('Casă / Vilă', 'Casă / Vilă'), ('Centru comercial', 'Centru comercial'), ('Hală / Depozit', 'Hală / Depozit'), ('Stradal', 'Stradal')], verbose_name='Tip imobil⋆'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Incompletă', 'Incompletă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Incompletă', verbose_name='Status proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='officespace',
            name='transaction_type',
            field=models.CharField(choices=[('Vânzare', 'Vânzare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție⋆'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='building_type',
            field=models.CharField(choices=[('Bloc de apartamente', 'Bloc de apartamente'), ('Bloc de garsoniere', 'Bloc de garsoniere'), ('Bloc mixt', 'Bloc mixt'), ('Vilă de apartamente', 'Vilă de apartamente'), ('Case / Vile', 'Case / Vile')], verbose_name='Tip imobil⋆'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='construction_materials',
            field=models.CharField(blank=True, choices=[('Beton', 'Beton'), ('Cărămidă', 'Cărămidă'), ('BCA', 'BCA'), ('Metal', 'Metal'), ('Lemn', 'Lemn'), ('Altele', 'Altele'), ('Cadre', 'Cadre'), ('Plăci', 'Plăci'), ('Monolit', 'Monolit')], null=True, verbose_name='Materiale construcție'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='construction_status',
            field=models.CharField(choices=[('Finalizată', 'Finalizată'), ('La gri', 'La gri'), ('La roșu', 'La roșu'), ('Structură', 'Structură'), ('Proiect', 'Proiect'), ('În construcție', 'În construcție'), ('De demolat', 'De demolat')], verbose_name='Stadiu construcție⋆'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='interior_finishes',
            field=models.CharField(choices=[('Finisat modern', 'Finisat modern'), ('Finisat', 'Finisat'), ('Finisat clasic', 'Finisat clasic'), ('Semifinisat', 'Semifinisat'), ('Necesită renovare', 'Necesită renovare'), ('Nefinisat', 'Nefinisat')], verbose_name='Stare interior⋆'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='other_spaces',
            field=models.CharField(blank=True, choices=[('Grădină proprie', 'Grădină proprie'), ('Boxă la subsol', 'Boxă la subsol'), ('Curte', 'Curte'), ('Curte comună', 'Curte comună'), ('Debara', 'Debara'), ('Lift', 'Lift'), ('Loc de joacă copii', 'Loc de joacă copii'), ('Magazie', 'Magazie'), ('Pivniță', 'Pivniță'), ('Zonă barbeque', 'Zonă barbeque')], null=True, verbose_name='Alte spații'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Incompletă', 'Incompletă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Incompletă', verbose_name='Status proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='residentialensemble',
            name='thermal_insulation',
            field=models.CharField(blank=True, choices=[('Izolație exterioară', 'Izolație exterioară'), ('Izolație interioară', 'Izolație interioară')], null=True, verbose_name='Izolație termică'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='VAT_rate',
            field=models.CharField(blank=True, choices=[('Nu se aplică TVA', 'Nu se aplică TVA'), ('TVA inclus', 'TVA inclus'), ('+ 9% TVA', '+ 9% TVA'), ('+ 19% TVA', '+ 19% TVA')], default='Nu se aplică TVA', null=True, verbose_name='TVA'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='classification',
            field=models.CharField(choices=[('Intravilan', 'Intravilan'), ('Extravilan', 'Extravilan')], verbose_name='Clasificare⋆'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='county',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Argeș', 'Argeș'), ('Arad', 'Arad'), ('București', 'București'), ('Bacău', 'Bacău'), ('Bihor', 'Bihor'), ('Bistrița-Năsăud', 'Bistrița-Năsăud'), ('Brăila', 'Brăila'), ('Botoșani', 'Botoșani'), ('Brașov', 'Brașov'), ('Buzău', 'Buzău'), ('Cluj', 'Cluj'), ('Călărași', 'Călărași'), ('Caraș-Severin', 'Caraș-Severin'), ('Constanța', 'Constanța'), ('Covasna', 'Covasna'), ('Dâmbovița', 'Dâmbovița'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Galați', 'Galați'), ('Giurgiu', 'Giurgiu'), ('Hunedoara', 'Hunedoara'), ('Harghita', 'Harghita'), ('Ilfov', 'Ilfov'), ('Ialomița', 'Ialomița'), ('Iași', 'Iași'), ('Mehedinți', 'Mehedinți'), ('Maramureș', 'Maramureș'), ('Mureș', 'Mureș'), ('Neamț', 'Neamț'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Sibiu', 'Sibiu'), ('Sălaj', 'Sălaj'), ('Satu-Mare', 'Satu-Mare'), ('Suceava', 'Suceava'), ('Tulcea', 'Tulcea'), ('Timiș', 'Timiș'), ('Teleorman', 'Teleorman'), ('Vâlcea', 'Vâlcea'), ('Vrancea', 'Vrancea'), ('Vaslui', 'Vaslui')], verbose_name='Județ⋆'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='currency',
            field=models.CharField(blank=True, choices=[('euro', '€'), ('lei', 'RON')], default='euro', null=True, verbose_name='Monedă'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='destination',
            field=models.CharField(blank=True, choices=[('Rezidențială', 'Rezidențială'), ('Comercială', 'Comercială'), ('Industrială', 'Industrială'), ('Agricolă', 'Agricolă'), ('Horeca / Retail', 'Horeca / Retail'), ('Spital / Clinică', 'Spital / Clinică'), ('Benzinărie', 'Benzinărie'), ('Spălătorie auto', 'Spălătorie auto'), ('De vacanță', 'De vacanță')], null=True, verbose_name='Destinație'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='land_facilities',
            field=models.CharField(blank=True, choices=[('Apă', 'Apă'), ('Canalizare', 'Canalizare'), ('Curent', 'Curent'), ('Gaz', 'Gaz'), ('Irigații', 'Irigații'), ('Utilități în zonă', 'Utilități în zonă')], null=True, verbose_name='Facilități teren'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='opening_to',
            field=models.CharField(blank=True, choices=[('Șosea', 'Șosea'), ('Drum principal', 'Drum principal'), ('DN', 'DN'), ('Autostradă', 'Autostradă'), ('Șoseaua de centură', 'Șoseaua de centură'), ('Lac', 'Lac'), ('Pădure', 'Pădure'), ('Drum de servitute', 'Drum de servitute')], null=True, verbose_name='Deschidere la'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='other_features',
            field=models.CharField(blank=True, choices=[('Acces auto', 'Acces auto'), ('Construcție demolabilă', 'Construcție demolabilă'), ('La șosea', 'La șosea'), ('Oportunitate de investiții', 'Oportunitate de investiții'), ('Parcelabil', 'Parcelabil'), ('Studiu Geo', 'Studiu Geo'), ('Teren împrejmuit', 'Teren împrejmuit')], null=True, verbose_name='Alte facilități'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='owner_type',
            field=models.CharField(blank=True, choices=[('Persoană fizică', 'Persoană fizică'), ('Persoană juridică', 'Persoană juridică')], null=True, verbose_name='Tip proprietar'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit ipotecar', 'Credit ipotecar'), ('Credit Prima Casă', 'Credit Prima Casă'), ('Rate la dezvoltator', 'Rate la dezvoltator')], null=True, verbose_name='Modalitate plată acceptată'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('terrain', 'Teren'), ('commercial_space', 'Spațiu comercial'), ('office_space', 'Spațiu de birouri'), ('industrial_space', 'Spațiu industrial')], default='apartment', verbose_name='Tip proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='status',
            field=models.CharField(choices=[('Activă', 'Activă'), ('Incompletă', 'Incompletă'), ('Retrasă', 'Retrasă'), ('Pierdută', 'Pierdută')], default='Incompletă', verbose_name='Status proprietate⋆'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='terrain_type',
            field=models.CharField(choices=[('Construcții', 'Construcții'), ('Agricol', 'Agricol'), ('Pădure', 'Pădure')], verbose_name='Tip teren⋆'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='transaction_type',
            field=models.CharField(choices=[('Vânzare', 'Vânzare'), ('Închiriere', 'Închiriere')], verbose_name='Tip tranzacție⋆'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='unit',
            field=models.CharField(choices=[('mp', 'mp'), ('ar', 'ar'), ('ha', 'ha')], verbose_name='Unitate suprafață⋆'),
        ),
    ]
